<?php
namespace App\Http\Controllers\BackEnd\Organizer;
use App\Http\Controllers\Controller;use App\Models\BoxOfficeHold;use App\Models\BoxOfficeSetting;use App\Models\Event;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class BoxOfficeOperationsController extends Controller{
 public function holds(){ $oid=auth('organizer')->id();$this->expire($oid);return response()->json(BoxOfficeHold::where('organizer_id',$oid)->where('status','held')->latest()->limit(50)->get());}
 public function hold(Request $r){$oid=auth('organizer')->id();$d=$r->validate(['event_id'=>'required|integer','location_id'=>'required|integer','items'=>'required|array|min:1','items.*.ticket_id'=>'required|integer','items.*.quantity'=>'required|integer|min:1','items.*.variation'=>'nullable|string|max:190','customer'=>'nullable|array']);$event=Event::where('organizer_id',$oid)->where('box_office_enabled',1)->findOrFail($d['event_id']);abort_unless($event->boxOfficeLocations()->whereKey($d['location_id'])->where('active',1)->exists(),422,'Invalid Box Office location.');$mins=(int)(BoxOfficeSetting::where('organizer_id',$oid)->where(function($q)use($event){$q->whereNull('event_id')->orWhere('event_id',$event->id);})->orderByRaw('event_id is null')->value('hold_minutes')?:10);$h=BoxOfficeHold::create(['uuid'=>(string)Str::uuid(),'organizer_id'=>$oid,'event_id'=>$event->id,'location_id'=>$d['location_id'],'items'=>$d['items'],'customer'=>$d['customer']??null,'status'=>'held','expires_at'=>now()->addMinutes(max(1,min($mins,120)))]);return response()->json($h,201);}
 public function resume($id){$oid=auth('organizer')->id();$this->expire($oid);$h=BoxOfficeHold::where('organizer_id',$oid)->where('status','held')->findOrFail($id);$h->update(['status'=>'resumed','resumed_at'=>now()]);return response()->json($h);}
 public function destroy($id){$oid=auth('organizer')->id();$h=BoxOfficeHold::where('organizer_id',$oid)->whereIn('status',['held','resumed'])->findOrFail($id);$h->update(['status'=>'cancelled']);return response()->json(['ok'=>true]);}
 public function settings(){ $oid=auth('organizer')->id();return view('organizer.box-office.settings',['setting'=>BoxOfficeSetting::firstOrCreate(['organizer_id'=>$oid,'event_id'=>null]),'events'=>Event::where('organizer_id',$oid)->where('box_office_enabled',1)->get()]);}
 public function updateSettings(Request $r){$oid=auth('organizer')->id();$d=$r->validate(['hold_minutes'=>'required|integer|min:1|max:120','receipt_width_mm'=>'required|in:58,80','allow_cash'=>'nullable|boolean','allow_upi'=>'nullable|boolean','allow_card'=>'nullable|boolean','allow_other'=>'nullable|boolean','require_customer_name'=>'nullable|boolean','require_customer_phone'=>'nullable|boolean','allow_aadhaar'=>'nullable|boolean','allow_customer_photo'=>'nullable|boolean','auto_email_ticket'=>'nullable|boolean']);foreach(['allow_cash','allow_upi','allow_card','allow_other','require_customer_name','require_customer_phone','allow_aadhaar','allow_customer_photo','auto_email_ticket'] as $k)$d[$k]=$r->boolean($k);BoxOfficeSetting::updateOrCreate(['organizer_id'=>$oid,'event_id'=>null],$d);return back()->with('success','POS settings updated.');}
 private function expire($oid){BoxOfficeHold::where('organizer_id',$oid)->where('status','held')->whereNotNull('expires_at')->where('expires_at','<=',now())->update(['status'=>'expired']);}
}