<?php
namespace App\Http\Controllers\BackEnd\Organizer;
use App\Http\Controllers\Controller;use App\Models\Event;use App\Models\OrganizerStaff;use App\Models\StaffAuditLog;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;
class StaffController extends Controller{
 public function index(){ $oid=auth('organizer')->id();return view('organizer.staff.index',['staff'=>OrganizerStaff::where('organizer_id',$oid)->with(['assignments.event','assignments.location'])->withCount('sales')->latest()->get(),'events'=>Event::where('organizer_id',$oid)->whereIn('event_type',['venue','box_office'])->with('boxOfficeLocations')->get(),'roles'=>config('staff.roles'),'departments'=>config('staff.departments'),'permissions'=>config('staff.permissions')]);}
 public function store(Request $r){$oid=auth('organizer')->id();$d=$this->validated($r,$oid);$event=$this->event($d['event_id'],$oid);$this->validateLocation($event,$d['box_office_location_id']??null,$d['role']);DB::transaction(function()use($r,$d,$oid){$profile=$this->profile($r,$d);$profile['organizer_id']=$oid;$profile['password']=Hash::make($d['password']);$profile['must_change_password']=true;$s=OrganizerStaff::create($profile);$s->assignments()->create(['event_id'=>$d['event_id'],'box_office_location_id'=>$d['box_office_location_id']??null]);$this->audit($s,'created');});return back()->with('success','Team member created.');}
 public function update(Request $r,$id){$oid=auth('organizer')->id();$s=OrganizerStaff::where('organizer_id',$oid)->findOrFail($id);$d=$this->validated($r,$oid,$s);$event=$this->event($d['event_id'],$oid);$this->validateLocation($event,$d['box_office_location_id']??null,$d['role']);DB::transaction(function()use($r,$s,$d){$s->update($this->profile($r,$d,$s));$s->assignments()->delete();$s->assignments()->create(['event_id'=>$d['event_id'],'box_office_location_id'=>$d['box_office_location_id']??null]);if(!$s->active)$s->tokens()->delete();$this->audit($s,'updated');});return back()->with('success','Team member updated.');}
 public function destroy($id){$oid=auth('organizer')->id();$s=OrganizerStaff::where('organizer_id',$oid)->findOrFail($id);$this->assertManageable($s);DB::transaction(function()use($s){$this->audit($s,'deleted',['name'=>$s->name,'username'=>$s->username]);$s->tokens()->delete();$s->update(['active'=>false,'name'=>$s->name.' [Archived]','username'=>'archived-'.$s->id.'-'.time(),'email'=>null,'phone'=>null,'photo'=>null,'notes'=>'Archived by organizer. Historical operational records retained.']);});return back()->with('success','Team member archived and access revoked. Historical sales remain recorded.');}
 public function resetPassword(Request $r,$id){$oid=auth('organizer')->id();$s=OrganizerStaff::where('organizer_id',$oid)->findOrFail($id);$this->assertManageable($s);$d=$r->validate(['password'=>'required|string|min:8|max:100']);$s->update(['password'=>Hash::make($d['password']),'must_change_password'=>true]);$s->tokens()->delete();$this->audit($s,'password_reset');return back()->with('success','Temporary password set. Existing staff sessions were revoked.');}
 private function validated(Request $r,$oid,$s=null){$d=$r->validate(['name'=>'required|string|max:120','username'=>['required','string','max:80',Rule::unique('organizer_staff')->where(fn($q)=>$q->where('organizer_id',$oid))->ignore(optional($s)->id)],'email'=>['nullable','email','max:190',Rule::unique('organizer_staff')->where(fn($q)=>$q->where('organizer_id',$oid))->ignore(optional($s)->id)],'phone'=>'nullable|string|max:30','password'=>[$s?'nullable':'required','string','min:8','max:100'],'role'=>['required',Rule::in(array_keys(config('staff.roles')))],'department'=>['required',Rule::in(array_keys(config('staff.departments')))],'job_title'=>'nullable|string|max:100','notes'=>'nullable|string|max:1000','active'=>'nullable|boolean','permissions'=>'nullable|array','permissions.*'=>['string',Rule::in(array_keys(config('staff.permissions')))],'event_id'=>'required|integer','box_office_location_id'=>'nullable|integer','photo'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:2048']);
  $this->assertGrantable($d,$s);
  return $d;}
 /**
  * A team member with team.manage may only hand out permissions they hold themselves, may not grant
  * team.manage, and may not change their own account or another manager's. The organizer is unrestricted.
  */
 private function assertGrantable(array $d,$target=null):void{
  $actor=auth('staff')->user(); if(!$actor) return;
  $requested=array_values($d['permissions']??config('staff.roles.'.$d['role'].'.permissions',[]));
  if(in_array('team.manage',$requested,true)) abort(403,'Only the organizer can grant team management.');
  $extra=array_diff($requested,$actor->permissions());
  if($extra) abort(403,'You cannot grant permissions you do not have: '.implode(', ',$extra));
  if($target&&((int)$target->id===(int)$actor->id||$target->hasPermission('team.manage'))) abort(403,'Only the organizer can change this team member.');
 }
 private function assertManageable($target):void{
  $actor=auth('staff')->user(); if(!$actor) return;
  if((int)$target->id===(int)$actor->id||$target->hasPermission('team.manage')) abort(403,'Only the organizer can change this team member.');
 }
 private function profile(Request $r,$d,$s=null){$x=['name'=>$d['name'],'username'=>$d['username'],'email'=>$d['email']??null,'phone'=>$d['phone']??null,'role'=>$d['role'],'department'=>$d['department'],'job_title'=>$d['job_title']??null,'notes'=>$d['notes']??null,'permissions'=>array_values($d['permissions']??config('staff.roles.'.$d['role'].'.permissions',[])),'active'=>$r->has('active')?$r->boolean('active'):true];if($r->hasFile('photo')){$x['photo']=$r->file('photo')->store('organizer-staff','public');}return $x;}
 private function event($id,$oid){
  // Any physical event can have team members (ticket checkers, credential issuers); POS roles are checked in validateLocation().
  return Event::where('organizer_id',$oid)->whereIn('event_type',['venue','box_office'])->findOrFail($id);}
 private function validateLocation($event,$location,$role){if(in_array($role,['sales_agent','cashier','box_office_supervisor'],true)&&!((int)$event->box_office_enabled===1||$event->event_type==='box_office'))abort(422,'Box Office is not enabled for this event.');if(in_array($role,['sales_agent','cashier','box_office_supervisor'],true)&&!$location)abort(422,'A Box Office location is required for this role.');if($location&&!$event->boxOfficeLocations()->whereKey($location)->exists())abort(422,'Invalid Box Office location.');}
 private function audit($s,$action,$meta=null){StaffAuditLog::create(['organizer_id'=>$s->organizer_id,'staff_id'=>$action==='deleted'?null:$s->id,'action'=>$action,'meta'=>$meta,'ip'=>request()->ip()]);}
}