@extends('organizer.layout')
@section('style')
<style>
:root{--pos-bg:#f4f6f9;--pos-card:#fff;--pos-text:#172033;--pos-muted:#6b7280;--pos-line:#e6e9ef;--pos-dark:#111827;--pos-accent:#ff8a1f;--pos-green:#10a84f}
.pos-wrap{margin:-30px -30px -15px;min-height:calc(100vh - 70px);background:var(--pos-bg);color:var(--pos-text);display:grid;grid-template-columns:82px minmax(0,1fr) 370px}
.pos-rail{background:#fff;border-right:1px solid var(--pos-line);padding:18px 8px;display:flex;flex-direction:column;gap:8px}
.pos-brand{font-weight:900;text-align:center;font-size:12px;padding:10px 0 18px}.pos-nav{border:0;background:transparent;border-radius:12px;padding:11px 4px;color:#596273;font-size:11px;text-align:center}.pos-nav i{display:block;font-size:20px;margin-bottom:6px}.pos-nav.active{background:#fff1e4;color:#d96d0b}.pos-main{padding:18px;min-width:0}.pos-top{display:flex;gap:12px;align-items:center;margin-bottom:18px}.pos-search{flex:1;background:#fff;border:1px solid var(--pos-line);border-radius:12px;padding:12px 15px}.pos-status{background:#eafaf0;color:#087a37;padding:8px 12px;border-radius:999px;font-weight:700;font-size:12px}.pos-section-title{font-size:18px;font-weight:800;margin:18px 0 10px}.event-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:14px}.event-card,.ticket-card{background:#fff;border:2px solid transparent;border-radius:16px;overflow:hidden;box-shadow:0 4px 16px rgba(17,24,39,.05);cursor:pointer;transition:.15s}.event-card:hover,.ticket-card:hover{transform:translateY(-2px);border-color:#ffd1a8}.event-card.active,.ticket-card.active{border-color:var(--pos-accent)}.event-img{height:118px;background:#e5e7eb center/cover no-repeat}.event-body{padding:12px}.event-title{font-weight:800;line-height:1.25}.event-meta{font-size:12px;color:var(--pos-muted);margin-top:6px}.session-row{display:flex;gap:8px;overflow:auto;padding-bottom:4px}.session{border:1px solid var(--pos-line);background:#fff;border-radius:10px;padding:9px 12px;white-space:nowrap;cursor:pointer}.session.active{background:var(--pos-dark);color:#fff}.ticket-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:12px}.ticket-card{padding:15px}.ticket-name{font-weight:800}.ticket-price{font-size:20px;font-weight:900;margin:8px 0}.ticket-stock{font-size:12px;color:var(--pos-muted)}.ticket-add{margin-top:12px;width:100%;border:0;border-radius:9px;background:#fff1e4;color:#c76105;padding:8px;font-weight:800}
.pos-cart{background:#fff;border-left:1px solid var(--pos-line);display:flex;flex-direction:column;min-height:calc(100vh - 70px)}.cart-head{padding:18px;border-bottom:1px solid var(--pos-line);display:flex;justify-content:space-between;align-items:center}.cart-head h5{margin:0;font-weight:900}.customer-chip{margin:14px 16px 0;border:1px dashed #cbd5e1;border-radius:12px;padding:11px;cursor:pointer}.customer-chip strong{display:block}.cart-lines{padding:12px 16px;flex:1;overflow:auto}.cart-empty{text-align:center;color:#9ca3af;padding:70px 20px}.cart-line{padding:12px 0;border-bottom:1px solid #eef0f3}.line-top{display:flex;justify-content:space-between;gap:8px}.line-name{font-weight:800}.line-controls{display:flex;align-items:center;gap:8px;margin-top:8px}.qty-btn{width:28px;height:28px;border:1px solid #ddd;background:#fff;border-radius:7px}.remove-line{margin-left:auto;border:0;background:none;color:#dc3545}.cart-summary{border-top:1px solid var(--pos-line);padding:15px 16px}.sum-row{display:flex;justify-content:space-between;margin:7px 0}.sum-total{font-size:19px;font-weight:900}.cart-actions{display:grid;grid-template-columns:1fr 1.35fr;gap:10px;margin-top:14px}.btn-hold{background:#fff1e4;color:#c76105;border:0;border-radius:11px;font-weight:800}.btn-pay{background:var(--pos-green);color:#fff;border:0;border-radius:11px;padding:14px;font-weight:900}.pos-modal{position:fixed;inset:0;background:rgba(17,24,39,.55);z-index:1100;display:none;align-items:center;justify-content:center;padding:18px}.pos-modal.open{display:flex}.pos-dialog{width:min(650px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:22px}.dialog-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.dialog-head h4{font-weight:900;margin:0}.close-x{border:0;background:#f3f4f6;border-radius:8px;width:34px;height:34px}.pay-methods{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.pay-method{border:1px solid var(--pos-line);background:#fff;border-radius:11px;padding:13px;font-weight:800}.pay-method.active{border-color:var(--pos-green);background:#edfff4;color:#087a37}.pay-total{text-align:center;font-size:36px;font-weight:900;margin:10px}.form-control{border-radius:9px}.hidden-native{display:none}.pos-mobile-cart{display:none}
@media(max-width:1100px){.pos-wrap{grid-template-columns:68px 1fr}.pos-cart{position:fixed;right:0;top:0;bottom:0;width:min(390px,94vw);z-index:1050;transform:translateX(100%);transition:.2s}.pos-cart.open{transform:none}.pos-mobile-cart{display:block;position:fixed;right:18px;bottom:18px;z-index:1040;border:0;border-radius:999px;background:var(--pos-green);color:#fff;padding:14px 18px;font-weight:900;box-shadow:0 8px 25px rgba(0,0,0,.2)}}@media(max-width:650px){.pos-wrap{margin:-30px -15px -15px;grid-template-columns:1fr}.pos-rail{display:none}.pos-main{padding:12px}.event-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.event-img{height:90px}.ticket-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pos-status{display:none}}
</style>
@endsection
@section('content')
@php
$posEvents=$events->map(function($e){return ['id'=>$e->id,'title'=>optional($e->information)->title ?: 'Event #'.$e->id,'image'=>asset('assets/admin/img/event/thumbnail-images/'.$e->thumbnail),'type'=>$e->event_type,'date_type'=>$e->date_type,'start_date'=>$e->start_date,'start_time'=>$e->start_time,'dates'=>$e->dates->map(fn($d)=>['value'=>$d->start_date.' '.$d->start_time,'label'=>date('d M',strtotime($d->start_date)).' · '.$d->start_time])->values(),'locations'=>$e->boxOfficeLocations->where('active',1)->map(fn($l)=>['id'=>$l->id,'name'=>$l->name])->values(),'tickets'=>$e->tickets->map(function($t){$vars=json_decode($t->variations,true)?:[];return ['id'=>$t->id,'title'=>$t->title ?: ($t->pricing_type==='variation'?'Ticket Options':'General Ticket'),'pricing_type'=>$t->pricing_type,'price'=>(float)($t->price??0),'available_type'=>$t->ticket_available_type,'available'=>$t->ticket_available,'variations'=>collect($vars)->map(fn($v)=>['name'=>$v['name']??'Option','price'=>(float)($v['price']??0),'available_type'=>$v['ticket_available_type']??'unlimited','available'=>$v['ticket_available']??null])->values()];})->values()];})->values();
@endphp
<div class="pos-wrap" id="posApp">
 <aside class="pos-rail"><div class="pos-brand">BookTKIT<br>POS</div><button class="pos-nav active"><i class="fas fa-home"></i>Home</button><button class="pos-nav" id="navEvents"><i class="fas fa-calendar-alt"></i>Events</button><a class="pos-nav" href="{{ route('organizer.event.booking') }}"><i class="fas fa-receipt"></i>Orders</a><a class="pos-nav" href="{{ route('organizer.boxoffice.shifts.index') }}"><i class="fas fa-cash-register"></i>Shifts</a><a class="pos-nav" href="{{ route('organizer.boxoffice.reports.index') }}"><i class="fas fa-chart-bar"></i>Reports</a><a class="pos-nav" href="{{ route('organizer.pwa') }}"><i class="fas fa-qrcode"></i>Scanner</a><a class="pos-nav" href="{{ route('organizer.dashboard') }}"><i class="fas fa-sign-out-alt"></i>Exit</a></aside>
 <main class="pos-main">
  @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
  <div class="pos-top"><input id="eventSearch" class="pos-search" placeholder="Search Box Office events..."><span class="pos-status"><i class="fas fa-wifi"></i> Online</span><button class="btn btn-dark" onclick="document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen()"><i class="fas fa-expand"></i></button></div>
  <div class="pos-section-title">Box Office Events</div><div class="event-grid" id="eventGrid"></div>
  <section id="saleArea" style="display:none"><div class="pos-section-title">Event Sessions</div><div class="session-row" id="sessions"></div><div class="pos-section-title">Tickets</div><div class="ticket-grid" id="tickets"></div></section>
 </main>
 <aside class="pos-cart" id="cartPanel"><div class="cart-head"><h5>Current Sale</h5><button class="close-x d-lg-none" id="closeCart">×</button></div><div class="customer-chip" id="customerOpen"><strong id="customerLabel">+ Add Customer</strong><span id="customerSub">Name and phone required</span></div><div class="cart-lines" id="cartLines"><div class="cart-empty"><i class="fas fa-ticket-alt fa-3x mb-3"></i><br>Select tickets to start a sale</div></div><div class="cart-summary"><div class="sum-row"><span>Ticket subtotal</span><strong id="subtotal">₹0.00</strong></div><div class="sum-row sum-total"><span>Estimated total</span><span id="grandTotal">₹0.00</span></div><small class="text-muted">Final price and fees are recalculated securely by BookTKIT when you pay.</small><div class="cart-actions"><button type="button" class="btn-hold" id="clearCart">Clear</button><button type="button" class="btn-pay" id="payOpen"><i class="fas fa-credit-card"></i> Pay <span id="payAmount">₹0.00</span></button></div></div></aside>
</div><button class="pos-mobile-cart" id="mobileCart"><i class="fas fa-shopping-cart"></i> Cart <span id="mobileQty">0</span></button>
<form id="saleForm" class="hidden-native" method="post" enctype="multipart/form-data" action="{{ route('organizer.boxoffice.store') }}">@csrf<input name="sale_uuid" value="{{ (string) Str::uuid() }}"><input name="event_id" id="fEvent"><input name="location_id" id="fLocation"><input name="event_date" id="fDate"><input name="customer_name" id="fName"><input name="customer_phone" id="fPhone"><input name="customer_email" id="fEmail"><input name="customer_age" id="fAge"><input name="aadhaar_number" id="fAadhaar"><input name="payment_method" id="fPayment"><input name="cash_received" id="fCash"><input name="deliver_email" id="fDeliver" value="0"><div id="fItems"></div><input type="file" name="aadhaar_document" id="fAadhaarDoc"><input type="file" name="customer_photo" id="fPhoto"></form>
<div class="pos-modal" id="customerModal"><div class="pos-dialog"><div class="dialog-head"><h4>Customer</h4><button class="close-x" data-close="customerModal">×</button></div><div class="row"><div class="col-md-6 form-group"><label>Name *</label><input id="cName" class="form-control"></div><div class="col-md-6 form-group"><label>Phone *</label><input id="cPhone" class="form-control"></div><div class="col-md-6 form-group"><label>Email</label><input id="cEmail" type="email" class="form-control"></div><div class="col-md-6 form-group"><label>Age</label><input id="cAge" type="number" min="1" max="120" class="form-control"></div><div class="col-md-6 form-group"><label>Aadhaar number <small>(optional)</small></label><input id="cAadhaar" maxlength="12" inputmode="numeric" class="form-control"></div><div class="col-md-6 form-group"><label>Aadhaar image/PDF <small>(optional)</small></label><input id="cAadhaarDoc" type="file" accept=".jpg,.jpeg,.png,.pdf" class="form-control"></div><div class="col-md-6 form-group"><label>Customer photo <small>(optional)</small></label><input id="cPhoto" type="file" accept="image/jpeg,image/png" capture="user" class="form-control"></div><div class="col-md-6 form-group pt-4"><label><input id="cDeliver" type="checkbox"> Email QR ticket after sale</label></div></div><button class="btn btn-dark btn-block" id="saveCustomer">Save Customer</button></div></div>
<div class="pos-modal" id="paymentModal"><div class="pos-dialog"><div class="dialog-head"><h4>Take Payment</h4><button class="close-x" data-close="paymentModal">×</button></div><div class="pay-total" id="paymentTotal">₹0.00</div><div class="pay-methods"><button class="pay-method active" data-method="cash">Cash</button><button class="pay-method" data-method="upi">UPI</button><button class="pay-method" data-method="card">Card</button><button class="pay-method" data-method="other">Other</button></div><div id="cashBox" class="mt-3"><label>Cash received</label><input id="cashReceived" type="number" min="0" step=".01" class="form-control form-control-lg"><div class="sum-row mt-2"><span>Change due</span><strong id="changeDue">₹0.00</strong></div></div><button class="btn btn-success btn-lg btn-block mt-3" id="completeSale">Payment received — Generate Tickets</button></div></div>
<script>
window.POS_EVENTS=@json($posEvents);
document.addEventListener('DOMContentLoaded',function(){
 const S={event:null,date:null,location:null,cart:[],customer:null,payment:'cash'};const q=s=>document.querySelector(s),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
 const eventGrid=q('#eventGrid'),sessions=q('#sessions'),tickets=q('#tickets'),saleArea=q('#saleArea');
 function renderEvents(filter=''){eventGrid.innerHTML='';POS_EVENTS.filter(e=>e.title.toLowerCase().includes(filter.toLowerCase())).forEach(e=>{const x=document.createElement('div');x.className='event-card'+(S.event&&S.event.id===e.id?' active':'');x.innerHTML='<div class="event-img" style="background-image:url(\''+e.image+'\')"></div><div class="event-body"><div class="event-title">'+esc(e.title)+'</div><div class="event-meta">'+(e.date_type==='multiple'?e.dates.length+' sessions':esc((e.start_date||'')+' '+(e.start_time||'')))+' · '+e.tickets.length+' ticket groups</div></div>';x.onclick=()=>selectEvent(e);eventGrid.appendChild(x)})}
 function selectEvent(e){S.event=e;S.cart=[];S.location=e.locations[0]?.id||null;S.date=null;renderEvents(q('#eventSearch').value);renderSessions();renderTickets();renderCart();saleArea.style.display='block'}
 function renderSessions(){let ds=S.event.date_type==='multiple'?S.event.dates:[{value:(S.event.start_date||'')+' '+(S.event.start_time||''),label:(S.event.start_date||'')+' · '+(S.event.start_time||'')}];sessions.innerHTML='';ds.forEach((d,i)=>{const b=document.createElement('button');b.className='session'+((S.date===d.value||(!S.date&&i===0))?' active':'');b.textContent=d.label;b.onclick=()=>{S.date=d.value;renderSessions()};sessions.appendChild(b)});if(!S.date&&ds[0])S.date=ds[0].value}
 function renderTickets(){tickets.innerHTML='';S.event.tickets.forEach(t=>{if(t.pricing_type==='variation'&&t.variations.length){t.variations.forEach(v=>ticketCard(t,v))}else ticketCard(t,null)})}
 function ticketCard(t,v){const name=v?v.name:t.title,price=t.pricing_type==='free'?0:(v?v.price:t.price),at=v?v.available_type:t.available_type,av=v?v.available:t.available;const sold=at==='limited'&&Number(av)<=0,x=document.createElement('div');x.className='ticket-card';x.innerHTML='<div class="ticket-name">'+esc(name)+'</div><div class="ticket-price">'+(price?money(price):'FREE')+'</div><div class="ticket-stock">'+(at==='limited'?(av+' available'):'Unlimited')+'</div><button class="ticket-add" '+(sold?'disabled':'')+'>'+(sold?'Sold out':'+ Add ticket')+'</button>';if(!sold)x.onclick=()=>add(t,v,price,name);tickets.appendChild(x)}
 function add(t,v,price,name){const key=t.id+'|'+(v?v.name:'');let line=S.cart.find(x=>x.key===key);if(line)line.qty++;else S.cart.push({key:key,ticket_id:t.id,variation:v?v.name:'',name:name,price:Number(price),qty:1});renderCart()}
 function renderCart(){const box=q('#cartLines');if(!S.cart.length)box.innerHTML='<div class="cart-empty"><i class="fas fa-ticket-alt fa-3x mb-3"></i><br>Select tickets to start a sale</div>';else{box.innerHTML='';S.cart.forEach((l,i)=>{const d=document.createElement('div');d.className='cart-line';d.innerHTML='<div class="line-top"><span class="line-name">'+esc(l.name)+'</span><strong>'+money(l.price*l.qty)+'</strong></div><div class="line-controls"><button class="qty-btn" data-a="-">−</button><strong>'+l.qty+'</strong><button class="qty-btn" data-a="+">+</button><button class="remove-line"><i class="fas fa-trash"></i></button></div>';d.querySelector('[data-a="-"]').onclick=()=>{l.qty--;if(l.qty<1)S.cart.splice(i,1);renderCart()};d.querySelector('[data-a="+"]').onclick=()=>{l.qty++;renderCart()};d.querySelector('.remove-line').onclick=()=>{S.cart.splice(i,1);renderCart()};box.appendChild(d)})}const total=S.cart.reduce((a,l)=>a+l.price*l.qty,0),qty=S.cart.reduce((a,l)=>a+l.qty,0);q('#subtotal').textContent=money(total);q('#grandTotal').textContent=money(total);q('#payAmount').textContent=money(total);q('#paymentTotal').textContent=money(total);q('#mobileQty').textContent=qty;calcChange()}
 function modal(id,on=true){q('#'+id).classList.toggle('open',on)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));q('#customerOpen').onclick=()=>modal('customerModal');q('#mobileCart').onclick=()=>q('#cartPanel').classList.add('open');q('#closeCart').onclick=()=>q('#cartPanel').classList.remove('open');
 q('#saveCustomer').onclick=()=>{const n=q('#cName').value.trim(),p=q('#cPhone').value.trim();if(!n||!p)return alert('Customer name and phone are required.');S.customer={name:n,phone:p,email:q('#cEmail').value.trim(),age:q('#cAge').value,aadhaar:q('#cAadhaar').value.trim(),deliver:q('#cDeliver').checked};q('#customerLabel').textContent=n;q('#customerSub').textContent=p+(S.customer.email?' · '+S.customer.email:'');modal('customerModal',false)};
 q('#payOpen').onclick=()=>{if(!S.event||!S.cart.length)return alert('Add at least one ticket.');if(!S.customer)return modal('customerModal');modal('paymentModal')};document.querySelectorAll('.pay-method').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pay-method').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.payment=b.dataset.method;q('#cashBox').style.display=S.payment==='cash'?'block':'none'});
 function calcChange(){const total=S.cart.reduce((a,l)=>a+l.price*l.qty,0),cash=Number(q('#cashReceived').value||0);q('#changeDue').textContent=money(Math.max(0,cash-total))}q('#cashReceived').oninput=calcChange;
 q('#completeSale').onclick=()=>{if(!S.customer)return alert('Add customer details first.');if(!S.location)return alert('This event has no active Box Office counter.');const total=S.cart.reduce((a,l)=>a+l.price*l.qty,0);if(S.payment==='cash'&&Number(q('#cashReceived').value||0)<total)return alert('Cash received is less than the displayed ticket subtotal.');q('#fEvent').value=S.event.id;q('#fLocation').value=S.location;q('#fDate').value=S.date||'';q('#fName').value=S.customer.name;q('#fPhone').value=S.customer.phone;q('#fEmail').value=S.customer.email;q('#fAge').value=S.customer.age;q('#fAadhaar').value=S.customer.aadhaar;q('#fPayment').value=S.payment;q('#fCash').value=q('#cashReceived').value||'';q('#fDeliver').value=S.customer.deliver?1:0;const fd=q('#fItems');fd.innerHTML='';S.cart.forEach((l,i)=>{[['ticket_id',l.ticket_id],['quantity',l.qty],['variation',l.variation]].forEach(([k,v])=>{const x=document.createElement('input');x.name='items['+i+']['+k+']';x.value=v;fd.appendChild(x)})});const ad=q('#cAadhaarDoc'),ph=q('#cPhoto');if(ad.files.length){const dt=new DataTransfer();dt.items.add(ad.files[0]);q('#fAadhaarDoc').files=dt.files}if(ph.files.length){const dt=new DataTransfer();dt.items.add(ph.files[0]);q('#fPhoto').files=dt.files}q('#completeSale').disabled=true;q('#saleForm').submit()};
 q('#clearCart').onclick=()=>{if(S.cart.length&&confirm('Clear the current cart?')){S.cart=[];renderCart()}};q('#eventSearch').oninput=e=>renderEvents(e.target.value);q('#navEvents').onclick=()=>q('#eventSearch').focus();function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}renderEvents();renderCart();
});
</script>
@endsection