const Map<String, String> arabic = {
  "Farthest first": "الأبعد أولاً",
  "Closest first": "الأقرب أولاً",
  "Distance": "مسافة",
  "Select City": "اختر المدينة",
  "Select State": "اختر الولاية",
  "Please wait we will send you a mail with an invoice":
      "من فضلك انتظر سوف نرسل لك رسالة بالبريد تحتوي على فاتورة",
  "PAYMENT STATUS": "يعالج",
  "PAYMENT METHOD": "يعالج",
  "TOTAL PAID": "يعالج",
  "COUPON": "يعالج",
  "EARLY BIRD": "يعالج",
  "TAX": "يعالج",
  "BOOKING ID": "يعالج",
  "BOOKING DATE": "يعالج",
  "Billing Address": "يعالج",
  "DURATION": "يعالج",
  "Bangla": "Bangla",
  "About Us": "معلومات عنا",
  "Shipping Status": "حالة الشحن",
  "processing": "يعالج",
  "Rating": "تقييم",
  "Blog Details": "تفاصيل المدونة",
  "Cart is empty": "البطاقه خاليه",
  "Over": "اكثر",
  "NOT RATED YET": "لم يتم تقييمه بعد",
  "Razorpay": "رازورباي",
  "Upcoming": "القادمه",
  "No data found for about section": "لم يتم العثور على بيانات عن القسم",
  "No data found for features section": "لا توجد بيانات عن قسم الميزات",
  "Already have an account": "هل لديك حساب",
  "Running": "جري",
  "linkedin": "لينكد إن",
  "Twitter": "تويتر",
  "Facebook": "فيس بوك",
  "Share Now": "شارك الآن",
  "Organised By": "نظمت من قبل",
  "Event Details": "تفاصيل الفعالية",
  "Event Start Date": "تاريخ بدء الحدث",
  "Ticket ID": "معرف التذكرة",
  "Order Date": "تاريخ الطلب",
  "Shipping Charge": "رسوم الشحن",
  "Total Paid": "مجموع المبالغ المدفوعة",
  "rejected": "مرفوض",
  "completed": "مكتمل",
  "pending": "قيد الانتظار",
  "Ticket": "تذكرة",
  "Booked Tickets": "التذاكر المحجوزة",
  "Payment Info": "معلومات الدفع",
  "Booking details": "تفاصيل الحجز",
  "Event Title": "عنوان الحدث",
  "Event Date": "تاريخ الحدث",
  "Support Tickets": "تذاكر الدعم الفني",
  "Product Orders": "طلبات المنتج",
  "Event Bookings": "حجوزات الأحداث",
  "Comment": "تعليق",
  "Enter Subject": "أدخل الموضوع",
  "Total Quantity": "الكمية الإجمالية",
  "Available Now": "متوفر في الوقت الحاضر",
  "Add this Event to Calendar": "أضف هذا الحدث إلى التقويم",
  "Proceed to Pay": "المضي قدما في الدفع",
  "Return Policy": "سياسة العائدات",
  "Our Partner": "شريكنا",
  "0 Clients Reviews": "0 آراء العملاء",
  "What say our client about us": "ماذا يقول عميلنا عنا",
  "Event Ticketing and Booking System": "نظام حجز التذاكر والفعاليات",
  "Featured Events": "فعاليات مميزة",
  "No Review Found": "لم يتم العثور على مراجعة",
  "Follow Me": "اتبعني",
  "till": "حتى",
  "Discount available": "الخصم متاح",
  "Select Tickets": "حدد التذاكر",
  "Yahoo": "ياهو",
  "Google Calendar": "تقويم جوجل",
  "Add to Calendar": "إضافة إلى التقويم",
  "View  Profile": "عرض الصفحة الشخصية",
  "The Event is Over": "انتهى الحدث",
  "The Event is Running": "الحدث جار",
  "Event Starts In": "يبدأ الحدث في",
  "GMT": "بتوقيت غرينيتش",
  "Select Date": "حدد تاريخ",
  "No Partner Found": "لم يتم العثور على شريك",
  "No Data Found for how work section":
      "لم يتم العثور على بيانات لكيفية قسم العمل",
  "Login": "تسجيل الدخول",
  "Signup": "اشتراك",
  "Enter Your Email Address": "أدخل عنوان بريدك الالكتروني",
  "Subscribe": "يشترك",
  "Useful Links": "روابط مفيدة",
  "No Link Found": "لم يتم العثور على ارتباط",
  "Latest Blog": "أحدث مدونة",
  "No Blog Found": "لم يتم العثور على مدونة",
  "No Testimonial Found": "لم يتم العثور على شهادة",
  "No Feature Found": "لم يتم العثور على ميزة",
  "Sort By": "ترتيب حسب",
  "Price": "سعر",
  "Ascending": "تصاعدي",
  "Descending": "تنازلي",
  "Free": "حر",
  "Categories": "فئات",
  "All Category": "كل الفئات",
  "Filter By Price": "تصفية حسب السعر",
  "By": "بواسطة",
  "Description": "وصف",
  "Frequently Asked Questions": "أسئلة مكررة",
  "No FAQ Found": "لا توجد أسئلة وأجوبة",
  "Submit": "يُقدِّم",
  "Discounted Price": "سعر مخفض",
  "Select Payment Gateway": "حدد بوابة الدفع",
  "Enter Your Card Number": "أدخل رقم بطاقتك",
  "Enter CVC Number": "أدخل رقم CVC",
  "Enter Expiry Month": "أدخل شهر انتهاء الصلاحية",
  "Enter Expiry Year": "أدخل سنة انتهاء الصلاحية",
  "Instructions": "تعليمات",
  "Attachment": "مرفق",
  "Enter Your Coupon": "أدخل الكوبون الخاص بك",
  "Apply": "يتقدم",
  "Close": "يغلق",
  "Search Blog": "مدونة البحث",
  "Search By Title": "البحث بالعنوان",
  "All": "الجميع",
  "Share": "يشارك",
  "Related Blog": "مدونة ذات صلة",
  "No Category Found": "لم يتم العثور على فئة",
  "Phone Number": "رقم الهاتف",
  "Email Address": "عنوان البريد الإلكتروني",
  "Location": "موقع",
  "Get In Touch": "ابقى على تواصل",
  "Enter Your Full Name": "أدخل اسمك الكامل",
  "Enter Your Email": "أدخل بريدك الإلكتروني",
  "Enter Email Subject": "أدخل موضوع البريد الإلكتروني",
  "Write Your Message": "اكتب رسالتك",
  "Send": "إرسال",
  "Logout": "تسجيل خروج",
  "Dashboard": "لوحة القيادة",
  "Account Information": "معلومات الحساب",
  "Name": "اسم",
  "Username": "اسم المستخدم",
  "Enter Your Username": "أدخل اسم المستخدم الخاص بك",
  "Email": "بريد إلكتروني",
  "Phone": "هاتف",
  "Address": "تبوك",
  "City": "مدينة",
  "State": "ولاية",
  "Country": "دولة",
  "Duration": "مدة",
  "Action": "فعل",
  "Back": "خلف",
  "Check": "الشيك",
  "Next": "التالي",
  "Edit Profile": "تعديل الملف الشخصي",
  "Edit Your Profile": "عدل ملفك الشخصي",
  "Upload": "رفع",
  "First Name": "الاسم الاول",
  "Last Name": "الكنية",
  "Contact Number": "رقم الاتصال",
  "Change Password": "تغيير كلمة المرور",
  "Current Password": "كلمة السر الحالية",
  "New Password": "كلمة المرور الجديدة",
  "Confirm New Password": "تأكيد كلمة المرور الجديدة",
  "Password": "كلمة المرور",
  "Enter Password": "أدخل كلمة المرور",
  "Lost your password": "فقدت كلمة المرور الخاصة بك",
  "Confirm Password": "تأكيد كلمة المرور",
  "Proceed": "يتابع",
  "Reset Password": "إعادة تعيين كلمة المرور",
  "Home": "مسكن",
  "Blog": "مدونة",
  "FAQ": "التعليمات",
  "Contact": "اتصال",
  "Page Not Found": "الصفحة غير موجودة",
  "Oops! Looks Like You Are Lost in Ocean": "أُووبس! يبدو أنك تائه في المحيط",
  "Get Back to Home": "ارجع الى المنزل",
  "No Related Blog Found": "لم يتم العثور على مدونة ذات صلة",
  "Print": "مطبعة",
  "Contact Us": "اتصل بنا",
  "Purchase History": "تاريخ شراء",
  "Order ID": "رقم التعريف الخاص بالطلب",
  "Date": "تاريخ",
  "Paid via": "دفع عن طريق",
  "Payment Status": "حالة السداد",
  "Invoice": "فاتورة",
  "Show": "يعرض",
  "Invoice Unavailable": "الفاتورة غير متوفرة",
  "Completed": "مكتمل",
  "Pending": "قيد الانتظار",
  "Rejected": "مرفوض",
  "None": "لا أحد",
  "Success": "نجاح",
  "Your transaction request was received and sent for review":
      "تم استلام طلب المعاملة الخاص بك وإرساله للمراجعة",
  "We answer every request as quickly as we can":
      "نحن نجيب على كل طلب بأسرع ما يمكن",
  "usually within 24–48 hours": "عادة في غضون 24-48 ساعة",
  "Thank you": "شكرًا لك",
  "Your Booking Request was Successfully Placed":
      "تم تقديم طلب الحجز الخاص بك بنجاح",
  "Please wait for confirmation": "يرجى انتظار التأكيد",
  "Your transaction was successful": "كانت معاملتك ناجحة",
  "We have sent you a mail with an invoice": "لقد أرسلنا لك بريدًا مع فاتورة",
  "Payment Success": "الدفع الناجح",
  "View More": "عرض المزيد",
  "Customer Login": "تسجيل دخول العميل",
  "Customer": "عميل",
  "Organizer": "منظم",
  "Organizer Login": "دخول المنظم",
  "Search Anything": "ابحث عن أي شيء",
  "Online": "متصل",
  "Our Events": "أحداثنا",
  "Events": "الأحداث",
  "Category": "فئة",
  "Online Events": "أحداث عبر الإنترنت",
  "Venue Events": "أحداث المكان",
  "Select Country": "حدد الدولة",
  "Filter by Date": "تصفية حسب التاريخ",
  "Price Filter": "مرشح السعر",
  "Admin": "مسؤل",
  "Event Is Running": "الحدث قيد التشغيل",
  "Event is Over": "انتهى الحدث",
  "View Profile": "عرض الصفحة الشخصية",
  "remaining": "متبقي",
  "No Event Found": "لا يوجد حدث",
  "Events Details": "تفاصيل الأحداث",
  "Description About This Event": "وصف حول هذا الحدث",
  "Location Map": "خريطة الموقع",
  "View Map": "إعرض الخريطة",
  "book now": "احجز الآن",
  "Book Now": "احجز الآن",
  "Add To Wishlist": "أضف إلى قائمة الامنيات",
  "Booking Details": "تفاصيل الحجز",
  "Booking ID": "معرف الحجز",
  "Booking Date": "تاريخ الحجز",
  "Event Name": "اسم الحدث",
  "Total Price": "السعر الكلي",
  "Early Bird Discount": "خصم الطيور في وقت مبكر",
  "Coupon Discount": "قسيمة تطبيق الخصم",
  "Payment Method": "طريقة الدفع او السداد",
  "Billing Details": "تفاصيل الفاتورة",
  "Checkout as Guest": "الخروج كضيف",
  "Don`t have an account": "ليس لديك أي حساب",
  "Signup Now": "أفتح حساب الأن",
  "Sign Up": "اشتراك",
  "Customer Signup": "تسجيل العميل",
  "Re-enter Password": "إعادة إدخال كلمة المرور",
  "Check Out": "الدفع",
  "Checkout": "الدفع",
  "Order Conformation": "تأكيد الطلب",
  "Order Summary": "ملخص الطلب",
  "total ticket": "إجمالي التذكرة",
  "sub total": "المجموع الفرعي",
  "Discount": "تخفيض",
  "Grand Total": "المجموع الإجمالي",
  "Coupon": "قسيمة",
  "Choose an Option": "إختر خيار",
  "Wishlist": "قائمة الرغبات",
  "My Bookings": "حجوزاتي",
  "My Orders": "طلباتي",
  "Support Ticket": "بطاقة الدعم",
  "Booking": "الحجز",
  "Paid Amount": "المبلغ المدفوع",
  "Total Early Bird Discount": "إجمالي الخصم المبكر",
  "Ticket Name": "اسم التذكرة",
  "Variation Name": "اسم الاختلاف",
  "Quantity": "كمية",
  "Wishlists": "قوائم الامنيات",
  "Remove": "يزيل",
  "Details": "تفاصيل",
  "No Events Found": "لم يتم العثور على أحداث",
  "My Booking": "الحجز",
  "Recent Bookings": "الحجوزات الأخيرة",
  "Booking Id": "معرف الحجز",
  "Status": "حالة",
  "My booking details": "تفاصيل حجزي",
  "Recent Orders": "الطلبيات الأخيرة",
  "Order Id": "رقم التعريف الخاص بالطلب",
  "Order Details": "تفاصيل الطلب",
  "My Order details": "تفاصيل طلبي",
  "Billing Information": "معلومات الفواتير",
  "Shipping Information": "معلومات الشحن",
  "Image": "صورة",
  "Product Name": "اسم المنتج",
  "Sku": "قكش",
  "No Product Found": "لم يتم العثور على منتج",
  "back": "خلف",
  "My Tickets": "تذاكري",
  "Ticket Number": "رقم التذكرة",
  "Subject": "موضوع",
  "Message": "رسالة",
  "No Tickets are Found": "لم يتم العثور على تذاكر",
  "Submit Ticket": "قدم التذكرة",
  "Submit a Ticket": "تسجيل التذكرة",
  "Support Ticket Details": "تفاصيل تذكرة الدعم",
  "Open": "يفتح",
  "Closed": "مغلق",
  "No Message Found": "لم يتم العثور على رسالة",
  "Max upload size 5 MB": "أقصى حجم تحميل 5 ميجا بايت",
  "Reply": "رد",
  "Enter Current Password": "إدخل كلمة السر الحالية",
  "Update": "تحديث",
  "Female": "أنثى",
  "Male": "ذكر",
  "Organizer Signup": "تسجيل المنظم",
  "Organizers": "المنظمون",
  "All Organizer": "كل المنظم",
  "Organizer Details": "تفاصيل المنظم",
  "Event History": "تاريخ الحدث",
  "No Events  Found": "لم يتم العثور على أحداث",
  "Shop": "محل",
  "Default Sorting": "الفرز الافتراضى",
  "Short by Latest": "باختصار بواسطة الأحدث",
  "Oldest Product": "أقدم منتج",
  "High To Low": "من الأعلى إلى الأقل",
  "Low To High": "من أسفل إلى أعلى",
  "Search": "يبحث",
  "Product Details": "تفاصيل المنتج",
  "Available": "متاح",
  "In Stock": "في الأوراق المالية",
  "Out of Stock": "إنتهى من المخزن",
  "SKU": "قكش",
  "Review": "مراجعة",
  "Add to Cart": "أضف إلى السلة",
  "Cart": "عربة التسوق",
  "Total Items": "إجمالي العناصر",
  "Cart Total": "إجمالي سلة التسوق",
  "Product": "منتج",
  "Availability": "التوفر",
  "update cart": "عربة التحديث",
  "checkout": "الدفع",
  "Same as the Shipping Address": "نفس عنوان الشحن",
  "Shipping Address": "عنوان الشحن",
  "Method": "طريقة",
  "Cost": "يكلف",
  "Order Total": "الطلب الكلي",
  "total Quantity": "الكمية الإجمالية",
  "Shipping Cost": "تكلفة الشحن",
  "Proceed to Payment": "الشروع في دفع",
  "Booking INVOICE": "فاتورة الحجز",
  "Quick Links": "روابط سريعة",
  "Send A Message": "ارسل رسالة",
  "Our Address": "عنواننا",
  "Our Email": "بريدنا الإلكتروني",
  "Our Phone": "هاتفنا",
  "Send Message": "أرسل رسالة",
  "Enter Your First Name": "أدخل اسمك الأول",
  "Enter Your Last Name": "أدخل اسمك الأخير",
  "Sorry, you are offline": "آسف ، أنت غير متصل بالإنترنت",
  "days": "أيام",
  "hour": "ساعة",
  "minutes": "دقائق",
  "seconds": "ثواني",
  "Event Duration": "مدة الحدث",
  "Enter Country, State, City": "أدخل البلد والولاية والمدينة",
  "Start/End Date": "تاريخ البدء / الانتهاء",
  "Map": "خريطة",
  "Related Events": "الأحداث ذات الصلة",
  "Read more": "اقرأ أكثر",
  "Read less": "أقرأ أقل",
  "Login with Facebook": "تسجيل الدخول باستخدام الفيسبوك",
  "Login with Google": "تسجيل الدخول عبر جوجل",
  "Login Now": "تسجيل الدخول الآن",
  "free": "حر",
  "Zip/Post Code": "الرمز البريدي / الرمز البريدي",
  "Tickets Info": "معلومات التذاكر",
  "Total Tickets": "إجمالي التذاكر",
  "Ticket Price": "سعر التذكرة",
  "Subtotal": "المجموع الفرعي",
  "Tax": "ضريبة",
  "Total": "المجموع",
  "Select a payment method": "اختر طريقة الدفع",
  "PayPal": "باي بال",
  "Instamojo": "إنستاموجو",
  "Paystack": "مكدس الرواتب",
  "Flutterwave": "رفرفة الموجة",
  "MercadoPago": "ميركادوباغو",
  "Mollie": "مولي",
  "Stripe": "شريط",
  "Paytm": "بايتم",
  "Citibank": "سيتي بنك",
  "Bank of America": "بنك امريكي",
  "Total organizer showing": "إجمالي المنظم يظهر",
  "Event": "حدث",
  "Enter Location": "إدخال الدولة",
  "Enter Username": "ادخل اسم المستخدم",
  "Enter Organizar Name": "أدخل اسم المنظمة",
  "About": "عن",
  "Total Events": "إجمالي الأحداث",
  "All Events": "كل الأحداث",
  "Contact Now": "اتصل الآن",
  "User": "المستعمل",
  "Download": "تحميل",
  "My Information": "معلوماتي",
  "Booking Tickets": "تذاكر الحجز",
  "Zip-code": "الرمز البريدي",
  "Product Ordered": "طلب المنتج",
  "Enter Reply": "أدخل الرد",
  "Replies": "الردود",
  "Return Home": "العودة للمنزل",
};
