<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>BookTKIT Team Dashboard</title><link rel="stylesheet" href="{{ asset('assets/admin/css/bootstrap.min.css') }}"><style>body{background:#f6f7fb}.module{height:100%;border:0;border-radius:14px}.perm{font-size:12px}.top{background:#fff;border-bottom:1px solid #e9ecef}</style></head><body>@include('staff.partials.impersonation-banner')
<div class="top"><div class="container py-3 d-flex justify-content-between align-items-center"><div><strong>BookTKIT Team Dashboard</strong><div class="text-muted small">{{ $staff->organizer->username }} · {{ $staff->name }} · {{ config('staff.roles.'.$staff->role.'.label') }}</div></div><form method="post" action="{{ route('staff.logout') }}">@csrf<button class="btn btn-sm btn-outline-danger">Logout</button></form></div></div>
<div class="container py-4">@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="row">
@if($staff->hasPermission('events.view'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Events</h5><p class="text-muted">View assigned organizer events.</p><a class="btn btn-primary" href="{{route('organizer.event_management.event')}}">Open Events</a></div></div></div>@endif
@if($staff->hasPermission('tickets.manage'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Tickets & Passes</h5><p class="text-muted">Manage ticket products and access settings.</p><a class="btn btn-primary" href="{{route('organizer.event.ticket')}}">Open Tickets</a></div></div></div>@endif
@if($staff->hasPermission('bookings.view'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Bookings</h5><p class="text-muted">View organizer event bookings.</p><a class="btn btn-primary" href="{{route('organizer.event.booking')}}">Open Bookings</a></div></div></div>@endif
@if($staff->hasPermission('box_office.sell'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Box Office POS</h5><p class="text-muted">Sell tickets for your assigned counters.</p><a class="btn btn-primary" href="{{route('staff.boxoffice.index')}}">Open POS</a></div></div></div><div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>My Shifts</h5><p class="text-muted">Open and close your cash shifts.</p><a class="btn btn-primary" href="{{route('staff.shifts.index')}}">Open Shifts</a></div></div></div>@endif
@if($staff->hasPermission('reports.view'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Reports</h5><p class="text-muted">View organizer Box Office reports.</p><a class="btn btn-primary" href="{{route('organizer.boxoffice.reports.index')}}">Open Reports</a></div></div></div>@endif
@if($staff->hasPermission('credentials.inventory'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Access Control</h5><p class="text-muted">Manage credential inventory and assignment.</p><a class="btn btn-primary" href="{{route('organizer.access.index')}}">Open Access</a></div></div></div>@endif
@if($staff->hasPermission('team.manage'))<div class="col-md-4 mb-3"><div class="card module"><div class="card-body"><h5>Team</h5><p class="text-muted">Manage organizer team accounts and permissions.</p><a class="btn btn-primary" href="{{route('organizer.staff.index')}}">Open Team</a></div></div></div>@endif
</div>
<div class="card"><div class="card-body"><h6>Your permissions</h6><div>@foreach($staff->permissions() as $p)<span class="badge badge-light perm mr-1 mb-1">{{ $permissions[$p] ?? $p }}</span>@endforeach</div><hr><strong>Assigned events</strong><ul class="mb-0 mt-2">@foreach($staff->assignments()->with(['event','location'])->get() as $a)<li>{{ optional($a->event)->title ?? 'Event #'.$a->event_id }} @if($a->location) — {{ $a->location->name }} @endif</li>@endforeach</ul></div></div>
</div></body></html>