<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Staff POS</title><link rel="stylesheet" href="{{ asset('assets/admin/css/bootstrap.min.css') }}"></head><body>@include('staff.partials.impersonation-banner')<div class="container py-4">
<div class="page-header"><h4 class="page-title">Box Office POS</h4></div>@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card"><div class="card-body"><form method="post" enctype="multipart/form-data" action="{{ route('staff.boxoffice.store') }}">@csrf<input type="hidden" name="sale_uuid" value="{{ (string) Str::uuid() }}">
<div class="row"><div class="col-md-6 form-group"><label>Box Office Event</label><select name="event_id" id="bo-event" class="form-control" required><option value="">Select</option>@foreach($events as $e)<option value="{{ $e->id }}">{{ optional($e->information)->title ?? 'Event #'.$e->id }}</option>@endforeach</select></div><div class="col-md-6 form-group"><label>Counter</label><select name="location_id" id="bo-location" class="form-control" required><option value="">Select</option>@foreach($events as $e)@foreach($e->boxOfficeLocations as $l)<option data-event="{{ $e->id }}" value="{{ $l->id }}">{{ $l->name }}</option>@endforeach @endforeach</select></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Customer name *</label><input name="customer_name" class="form-control" required></div><div class="col-md-4 form-group"><label>Phone *</label><input name="customer_phone" class="form-control" required></div><div class="col-md-4 form-group"><label>Email</label><input name="customer_email" type="email" class="form-control"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Age</label><input type="number" min="1" max="120" name="customer_age" class="form-control"></div><div class="col-md-3 form-group" @if(empty(($posSettings ?? \App\Services\BoxOffice\BoxOfficeSaleInput::DEFAULTS)[\'allow_aadhaar\'])) hidden @endif><label>Aadhaar number (optional)</label><input name="aadhaar_number" inputmode="numeric" maxlength="12" pattern="[0-9]{12}" class="form-control" autocomplete="off"></div><div class="col-md-3 form-group" @if(empty(($posSettings ?? \App\Services\BoxOffice\BoxOfficeSaleInput::DEFAULTS)[\'allow_aadhaar\'])) hidden @endif><label>Aadhaar photo/PDF (optional)</label><input type="file" name="aadhaar_document" accept=".jpg,.jpeg,.png,.pdf" class="form-control"></div><div class="col-md-3 form-group" @if(empty(($posSettings ?? \App\Services\BoxOffice\BoxOfficeSaleInput::DEFAULTS)[\'allow_customer_photo\'])) hidden @endif><label>Customer photo (optional)</label><input type="file" name="customer_photo" accept="image/jpeg,image/png" capture="user" class="form-control"></div></div>
<div class="row"><div class="col-md-6 form-group"><label>Event date/session *</label><select name="event_date" id="bo-date" class="form-control" required><option value="">Select date</option>@foreach($events as $e)@if($e->date_type==='multiple')@foreach($e->dates as $d)<option data-event="{{ $e->id }}" value="{{ $d->start_date }} {{ $d->start_time }}">{{ $d->start_date }} {{ $d->start_time }}</option>@endforeach @else<option data-event="{{ $e->id }}" value="{{ $e->start_date }} {{ $e->start_time }}">{{ $e->start_date }} {{ $e->start_time }}</option>@endif @endforeach</select></div><div class="col-md-6 form-group"><label>Ticket type *</label><select name="items[0][ticket_id]" id="bo-ticket" class="form-control" required><option value="">Select ticket</option>@foreach($events as $e)@foreach($e->tickets as $t)<option data-event="{{ $e->id }}" value="{{ $t->id }}">{{ $t->title ?? ('Ticket #'.$t->id) }} — {{ $t->pricing_type==='free' ? 'FREE' : number_format((float)$t->price,2) }} @if($t->ticket_available_type==='limited') ({{ $t->ticket_available }} left) @endif</option>@endforeach @endforeach</select></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Quantity *</label><input type="number" min="1" value="1" name="items[0][quantity]" class="form-control" required></div><div class="col-md-4 form-group"><label>Payment *</label><select name="payment_method" class="form-control">@foreach(\App\Services\BoxOffice\BoxOfficeSaleInput::allowedMethods($posSettings ?? \App\Services\BoxOffice\BoxOfficeSaleInput::DEFAULTS) as $pmKey)<option value="{{ $pmKey }}">{{ ['cash' => 'Cash', 'upi' => 'UPI', 'card' => 'Card', 'other' => 'Other'][$pmKey] }}</option>@endforeach</select></div><div class="col-md-4 form-group form-check pt-4"><input type="hidden" name="deliver_email" value="0"><input class="form-check-input" type="checkbox" name="deliver_email" value="1" id="deliverEmail"><label class="form-check-label" for="deliverEmail">Email QR ticket</label></div></div>
<button class="btn btn-success btn-lg btn-block">Payment received — Generate Ticket</button></form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const e=document.getElementById('bo-event');function f(id,sel){[...sel.options].forEach((o,i)=>{if(i)o.hidden=o.dataset.event!==id});sel.value=''}e.addEventListener('change',()=>{f(e.value,document.getElementById('bo-location'));f(e.value,document.getElementById('bo-ticket'));f(e.value,document.getElementById('bo-date'))})})</script>
@endsection