<?php
namespace App\Services\BoxOffice;
use App\Models\BoxOfficeSale;use App\Models\Event;use App\Models\Event\Booking;use App\Models\Payments\OrganizerPaymentProfile;use App\Services\Payments\AuthoritativeTicketPricingService;use App\Services\Payments\PlatformFeeCalculator;use App\Services\Tickets\TicketIssuanceService;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;use App\Services\Tickets\TicketDeliveryService;
class BoxOfficeSaleService{
 public function __construct(private AuthoritativeTicketPricingService $pricing,private PlatformFeeCalculator $fees,private LockedTicketInventoryService $inventory,private TicketIssuanceService $issuance,private BoxOfficeLedgerService $ledger){}
 public function sell(array $data,int $organizerId,?int $staffId=null):BoxOfficeSale{
  if($existing=BoxOfficeSale::where('uuid',$data['sale_uuid'])->first())return $existing;
  $sale=DB::transaction(function()use($data,$organizerId,$staffId){if($existing=BoxOfficeSale::where('uuid',$data['sale_uuid'])->lockForUpdate()->first())return $existing;$event=Event::whereKey($data['event_id'])->where('organizer_id',$organizerId)->where('box_office_enabled',1)->firstOrFail();if(!$event->boxOfficeLocations()->whereKey($data['location_id'])->where('active',1)->exists())throw ValidationException::withMessages(['location_id'=>'Invalid box office location.']);$this->inventory->reserve($event->id,$data['items']);$quote=$this->pricing->quote($event->id,$data['items']);$fee=$this->fees->calculate($quote['ticket_amount'],OrganizerPaymentProfile::where('organizer_id',$organizerId)->first());$first=$quote['items'][0];$booking=Booking::create(['booking_id'=>'BO-'.strtoupper(substr(str_replace('-','',$data['sale_uuid']),0,12)),'event_id'=>$event->id,'organizer_id'=>$organizerId,'ticket_id'=>$first['ticket_id'],'fname'=>$data['customer_name'],'phone'=>$data['customer_phone'],'email'=>$data['customer_email']??null,'quantity'=>$quote['quantity'],'price'=>$quote['ticket_amount']/100,'discount'=>$quote['discount']/100,'paymentMethod'=>$data['payment_method'],'gatewayType'=>'box_office','paymentStatus'=>'completed','booking_source'=>'box_office','sold_by_staff_id'=>$staffId,'box_office_location_id'=>$data['location_id'],'sale_uuid'=>$data['sale_uuid'],'counter_payment_method'=>$data['payment_method'],'variation'=>json_encode(array_map(fn($i)=>['ticket_id'=>$i['ticket_id'],'name'=>$i['variation']?:'Ticket','qty'=>$i['quantity']],$quote['items']))]);$sale=BoxOfficeSale::create(['uuid'=>$data['sale_uuid'],'booking_id'=>$booking->id,'event_id'=>$event->id,'organizer_id'=>$organizerId,'staff_id'=>$staffId,'location_id'=>$data['location_id'],'payment_method'=>$data['payment_method'],'ticket_amount'=>$quote['ticket_amount'],'platform_fee'=>$fee['platform_fee'],'customer_total'=>$fee['customer_total'],'organizer_amount'=>$fee['organizer_amount'],'pricing_snapshot'=>$quote['items']]);$this->issuance->ensureForBooking($booking);$sale->logs()->create(['action'=>'sale_created','actor_staff_id'=>$staffId,'actor_organizer_id'=>$staffId?null:$organizerId]);$this->ledger->recordSale($sale);return $sale;});
  if(!empty($data['deliver_email'])&&!empty($sale->booking->email))$this->delivery->deliver($sale->booking);
  return $sale;
 }
}