@extends('organizer.layout')
@section('content')
<div class="page-header"><h4 class="page-title">Payments & Settlements</h4><p class="text-muted">Your ticket sales remain active even while Razorpay verification is pending.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row">
@foreach(['gross'=>'Gross Sales','payable'=>'Net Earnings','fees'=>'Platform Fees','additional'=>'Additional Fees','booktkit_held'=>'BookTKIT-held','routed'=>'Razorpay Routed','refunds'=>'Refunds'] as $key=>$label)
<div class="col-md-3 mb-3"><div class="card h-100"><div class="card-body"><small>{{ $label }}</small><h3>₹{{ number_format($summary[$key]/100,2) }}</h3></div></div></div>
@endforeach
</div>
<div class="card mb-4"><div class="card-header"><div class="card-title">Preferred Settlement Method</div></div><div class="card-body">
<form method="POST" action="{{ route('organizer.payments.preference') }}">@csrf
<div class="row"><div class="col-md-5"><label class="d-block border rounded p-3"><input type="radio" name="preferred_settlement_mode" value="booktkit_managed" {{ ($profile->preferred_settlement_mode?:$profile->settlement_mode)==='booktkit_managed'?'checked':'' }}> <strong>BookTKIT Managed</strong><br><small>Sell immediately. BookTKIT collects customer payments and settles your eligible balance.</small></label></div>
<div class="col-md-5"><label class="d-block border rounded p-3"><input type="radio" name="preferred_settlement_mode" value="razorpay_split" {{ ($profile->preferred_settlement_mode?:$profile->settlement_mode)==='razorpay_split'?'checked':'' }}> <strong>Razorpay Direct</strong><br><small>BookTKIT checkout with automated Razorpay Route allocation after verification.</small></label></div><div class="col-md-2"><button class="btn btn-primary mt-4">Save</button></div></div></form>
<div class="card mt-4"><div class="card-header"><h5 class="mb-0">Your BookTKIT Fee Schedule</h5></div><div class="card-body"><p class="text-muted">These are the active platform and channel fees that can apply to your new ticket sales. The most specific matching rule is used at checkout.</p><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Applies to</th><th>Channel</th><th>Platform fee</th><th>Fixed / ticket</th><th>Paid by</th></tr></thead><tbody>@forelse($feeRules as $r)<tr><td>@if($r->scope==='event'){{ $eventNames[$r->event_id] ?? 'Specific event' }}@elseif($r->scope==='event_type'){{ ucfirst(str_replace('_',' ',$r->event_type)) }} events @elseif($r->scope==='organizer')Your organizer account @else All events @endif</td><td>{{ strtoupper($r->sales_channel==='any'?'All':$r->sales_channel) }}</td><td>{{ rtrim(rtrim(number_format($r->percentage,2),'0'),'.') }}%</td><td>₹{{ number_format(($r->fixed_amount??0)/100,2) }} @if(($r->per_ticket_amount??0)>0)+ ₹{{number_format($r->per_ticket_amount/100,2)}} / ticket @endif</td><td>{{ $r->fee_bearer==='additional'?'Customer':'Organizer' }}</td></tr>@empty<tr><td colspan="5">No explicit fee rule is currently configured for your account.</td></tr>@endforelse</tbody></table></div>@if($additionalFees->count())<h6 class="mt-4">Event charges</h6><div class="table-responsive"><table class="table"><thead><tr><th>Event</th><th>Charge</th><th>Amount</th><th>Applied</th><th>Paid by</th></tr></thead><tbody>@foreach($additionalFees as $fee)<tr><td>{{$eventNames[$fee->event_id]??'Event'}}</td><td>{{$fee->name}}</td><td>@if($fee->percentage){{$fee->percentage}}% @else ₹{{number_format($fee->fixed_amount/100,2)}} @endif</td><td>{{str_replace('_',' ',$fee->application)}}</td><td>{{ucfirst($fee->fee_bearer)}}</td></tr>@endforeach</tbody></table></div>@endif</div></div>
<hr><div class="row"><div class="col-md-3"><small>Razorpay verification</small><h5>{{ ucfirst(str_replace('_',' ',$profile->razorpay_status)) }}</h5></div><div class="col-md-3"><small>Current collection mode</small><h5>{{ $profile->canSplit() && ($profile->preferred_settlement_mode?:$profile->settlement_mode)==='razorpay_split'?'Razorpay Direct':'BookTKIT Managed' }}</h5></div><div class="col-md-3"><small>Ticket sales</small><h5 class="text-success">ACTIVE</h5></div><div class="col-md-3"><small>Automatic Route settlement</small><h5>{{ $profile->canSplit()?'Available':'Pending verification' }}</h5></div></div>
@if(($profile->preferred_settlement_mode?:$profile->settlement_mode)==='razorpay_split'&&!$profile->canSplit())<div class="alert alert-warning mt-3 mb-0"><strong>Automatic fallback active.</strong> Razorpay Direct is your preference, but verification/Route eligibility is not active. New sales are being collected using BookTKIT Managed. When eligibility becomes active, new transactions can route directly; previous transactions keep their original settlement mode.</div>@endif
</div></div>
<div class="card"><div class="card-header"><div class="card-title">Transactions & Settlement</div></div><div class="card-body table-responsive"><table class="table"><thead><tr><th>Payment</th><th>Channel</th><th>Gross</th><th>Fees</th><th>Your Amount</th><th>Collection</th><th>Status</th><th>Refunds</th></tr></thead><tbody>
@forelse($orders as $o)<tr><td>{{ $o->gateway_payment_id ?: $o->uuid }}</td><td>{{ strtoupper($o->sales_channel?:'web') }}</td><td>₹{{ number_format($o->ticket_amount/100,2) }}</td><td>₹{{ number_format(($o->platform_fee+$o->additional_fee_amount)/100,2) }}</td><td>₹{{ number_format($o->organizer_amount/100,2) }}</td><td>{{ $o->settlement_mode==='razorpay_split'?'Razorpay Direct':'BookTKIT Managed' }}<br><small>{{ $o->settlement_reason }}</small></td><td>{{ $o->status }}</td><td>₹{{ number_format($o->refunded_amount/100,2) }}</td></tr>@empty<tr><td colspan="8">No payments yet.</td></tr>@endforelse
</tbody></table>{{ $orders->links() }}</div></div>
@endsection