@extends('backend.layout')
@section('content')
<div class="page-header"><h4 class="page-title">Payments & Finance V2</h4><p class="text-muted mb-0">One policy engine for web, mobile and POS. Amounts are snapshotted on each payment order.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row">
@foreach(['paid'=>'Customer Payments','platform'=>'BookTKIT Revenue','organizer'=>'Organizer Payable','refunded'=>'Refunded'] as $key=>$label)
<div class="col-md-3"><div class="card"><div class="card-body"><small>{{ $label }}</small><h3>₹{{ number_format($summary[$key]/100,2) }}</h3></div></div></div>
@endforeach
</div>
<div class="card mb-4"><div class="card-header"><div class="card-title">Fee Policy</div><small class="text-muted">Specific event rules override organizer rules; organizer rules override global rules. Event type/channel specificity wins inside each scope.</small></div>
<div class="card-body">
<form method="POST" action="{{ route('admin.payments.fee_rules.store') }}">@csrf
<div class="row">
<div class="col-md-3"><label>Name</label><input class="form-control" name="name" required placeholder="Venue web standard"></div>
<div class="col-md-2"><label>Scope</label><select class="form-control" name="scope_type"><option value="global">Global</option><option value="organizer">Organizer</option><option value="event">Event</option></select></div>
<div class="col-md-2"><label>Scope ID</label><input class="form-control" type="number" min="1" name="scope_id" placeholder="Optional for global"></div>
<div class="col-md-2"><label>Event type</label><select class="form-control" name="event_type"><option value="">Any</option><option value="online">Online</option><option value="venue">Venue</option><option value="box_office">Box Office</option></select></div>
<div class="col-md-2"><label>Channel</label><select class="form-control" name="sales_channel"><option value="">Any</option><option value="web">Web</option><option value="mobile">Mobile</option><option value="pos">POS</option></select></div>
</div>
<div class="row mt-3">
<div class="col-md-2"><label>Percentage %</label><input class="form-control" type="number" step="0.0001" min="0" max="100" name="percentage" value="0" required></div>
<div class="col-md-2"><label>Fixed ₹</label><input class="form-control" type="number" step="0.01" min="0" name="fixed_amount_rupees" value="0" required></div>
<div class="col-md-2"><label>Charged to</label><select class="form-control" name="fee_bearer"><option value="organizer">Organizer</option><option value="customer">Customer</option></select></div>
<div class="col-md-2"><label>Priority</label><input class="form-control" type="number" min="0" name="priority" value="0" required></div>
<div class="col-md-2"><label>Starts</label><input class="form-control" type="datetime-local" name="effective_from"></div>
<div class="col-md-2"><label>Ends</label><input class="form-control" type="datetime-local" name="effective_until"></div>
</div><input type="hidden" name="enabled" value="1"><button class="btn btn-primary mt-3">Create Fee Rule</button>
</form>
<hr>
<div class="table-responsive"><table class="table table-striped"><thead><tr><th>Rule</th><th>Scope</th><th>Event</th><th>Channel</th><th>Fee</th><th>Bearer</th><th>Priority</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($feeRules as $rule)<tr><td>{{ $rule->name }}</td><td>{{ $rule->scope_type }}{{ $rule->scope_id ? ' #'.$rule->scope_id : '' }}</td><td>{{ $rule->event_type ?: 'Any' }}</td><td>{{ $rule->sales_channel ?: 'Any' }}</td><td>{{ rtrim(rtrim(number_format($rule->percentage,4),'0'),'.') }}% + ₹{{ number_format($rule->fixed_amount/100,2) }}</td><td>{{ ucfirst($rule->fee_bearer) }}</td><td>{{ $rule->priority }}</td><td>v{{ $rule->version }}</td><td><span class="badge {{ $rule->enabled?'badge-success':'badge-secondary' }}">{{ $rule->enabled?'Active':'Disabled' }}</span></td><td>@if($rule->enabled)<form method="POST" action="{{ route('admin.payments.fee_rules.destroy',$rule->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Disable this rule for new orders?')">Disable</button></form>@endif</td></tr>
@empty<tr><td colspan="10" class="text-center">No V2 fee rules yet. Legacy organizer fee settings remain the fallback until a matching rule exists.</td></tr>@endforelse
</tbody></table></div></div></div>
<div class="card mb-4"><div class="card-header"><div class="card-title">Additional Fees</div><small class="text-muted">Wristbands, RFID cards, physical passes, parking, delivery and other event charges.</small></div><div class="card-body">
<form method="POST" action="{{ route('admin.payments.additional_fees.store') }}">@csrf
<div class="row"><div class="col-md-2"><label>Event ID</label><input class="form-control" type="number" min="1" name="event_id" required></div><div class="col-md-2"><label>Code</label><input class="form-control" name="code" placeholder="wristband" required></div><div class="col-md-2"><label>Name</label><input class="form-control" name="name" placeholder="Wristband" required></div><div class="col-md-2"><label>Calculation</label><select class="form-control" name="calculation_type"><option value="fixed_per_order">Fixed / order</option><option value="fixed_per_ticket">Fixed / ticket</option><option value="percentage">Percentage</option></select></div><div class="col-md-2"><label>Fixed ₹</label><input class="form-control" type="number" step=".01" min="0" name="fixed_amount_rupees" value="0"></div><div class="col-md-2"><label>Percentage</label><input class="form-control" type="number" step=".0001" min="0" max="100" name="percentage" value="0"></div></div>
<div class="row mt-3"><div class="col-md-2"><label>Charged to</label><select class="form-control" name="fee_bearer"><option value="customer">Customer</option><option value="organizer">Organizer</option></select></div><div class="col-md-4"><label>Channels</label><div><label class="mr-3"><input type="checkbox" name="sales_channels[]" value="web"> Web</label><label class="mr-3"><input type="checkbox" name="sales_channels[]" value="mobile"> Mobile</label><label><input type="checkbox" name="sales_channels[]" value="pos"> POS</label></div></div><div class="col-md-2"><label><input type="checkbox" name="mandatory" value="1"> Mandatory</label></div><div class="col-md-2"><label><input type="checkbox" name="taxable" value="1"> Taxable</label></div></div><button class="btn btn-primary mt-3">Save Additional Fee</button></form>
<div class="table-responsive mt-4"><table class="table table-striped"><thead><tr><th>Event</th><th>Fee</th><th>Calculation</th><th>Bearer</th><th>Channels</th><th>Required</th><th>Status</th><th></th></tr></thead><tbody>@forelse($additionalFees as $fee)<tr><td>#{{ $fee->event_id }}</td><td>{{ $fee->name }} <small>({{ $fee->code }})</small></td><td>{{ $fee->calculation_type }} @if($fee->percentage) {{ $fee->percentage }}% @endif @if($fee->fixed_amount) ₹{{ number_format($fee->fixed_amount/100,2) }} @endif</td><td>{{ ucfirst($fee->fee_bearer) }}</td><td>{{ $fee->sales_channels ? implode(', ',$fee->sales_channels) : 'All' }}</td><td>{{ $fee->mandatory?'Yes':'Optional' }}</td><td>{{ $fee->enabled?'Active':'Disabled' }}</td><td>@if($fee->enabled)<form method="POST" action="{{ route('admin.payments.additional_fees.destroy',$fee->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Disable</button></form>@endif</td></tr>@empty<tr><td colspan="8" class="text-center">No additional fees configured.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="card"><div class="card-header"><div class="card-title">Payment Orders & Settlement</div></div><div class="card-body table-responsive">
<table class="table table-striped"><thead><tr><th>Order</th><th>Channel</th><th>Organizer</th><th>Customer Paid</th><th>BookTKIT</th><th>Organizer</th><th>Status</th><th>Settlement</th><th>Fallback / Route reason</th></tr></thead><tbody>
@forelse($orders as $o)<tr><td><small>{{ $o->uuid }}</small></td><td>{{ strtoupper($o->sales_channel ?: 'web') }}</td><td>{{ $o->organizer_id ?: 'BookTKIT' }}</td><td>₹{{ number_format($o->customer_total/100,2) }}</td><td>₹{{ number_format($o->booktkit_revenue/100,2) }}</td><td>₹{{ number_format($o->organizer_amount/100,2) }}</td><td><span class="badge badge-info">{{ $o->status }}</span></td><td>{{ $o->settlement_mode }} @if($o->transfers->count()) / {{ $o->transfers->last()->status }} @endif</td><td><small>{{ $o->settlement_reason ?: 'legacy' }}</small></td></tr>
@empty<tr><td colspan="9" class="text-center">No BookTKIT payment orders yet.</td></tr>@endforelse
</tbody></table>{{ $orders->links() }}</div></div>
@endsection