@extends('backend.layout')
@section('content')
<style>
.finance-shell{max-width:1500px;margin:auto}.finance-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:18px}.finance-head h3{margin:0}.finance-tabs,.pricing-tabs{display:flex;gap:8px;overflow-x:auto;padding-bottom:5px}.finance-tabs button,.pricing-tabs button{white-space:nowrap;border:1px solid rgba(255,255,255,.12);background:transparent;color:inherit;border-radius:10px;padding:10px 16px;cursor:pointer}.finance-tabs button.active,.pricing-tabs button.active{background:#1572e8;color:#fff;border-color:#1572e8}.finance-panel,.pricing-panel{display:none}.finance-panel.active,.pricing-panel.active{display:block}.metric-card{height:100%;border-radius:14px}.metric-card small{opacity:.7}.metric-card h3{margin:8px 0 0}.simple-card{border-radius:14px}.setting-card{border:1px solid rgba(127,127,127,.2);border-radius:12px;padding:18px;height:100%}.setting-card h5{margin-bottom:4px}.help{font-size:12px;opacity:.65}.fee-row{display:flex;justify-content:space-between;align-items:center;gap:15px;border-bottom:1px solid rgba(127,127,127,.15);padding:14px 0}.fee-row:last-child{border:0}.status-pill{padding:4px 9px;border-radius:20px;font-size:11px;background:rgba(21,114,232,.15)}.mobile-transactions{display:none}.advanced-note{font-size:11px;opacity:.55}.flow{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.flow span{padding:10px 14px;border-radius:10px;background:rgba(127,127,127,.12)}.flow b{opacity:.4}.modal-content{border-radius:14px}
@media(max-width:767px){.finance-head{align-items:flex-start;flex-direction:column}.finance-shell{padding:0 2px}.metric-card h3{font-size:20px}.desktop-transactions{display:none}.mobile-transactions{display:block}.txn-card{border:1px solid rgba(127,127,127,.18);border-radius:12px;padding:14px;margin-bottom:10px}.txn-line{display:flex;justify-content:space-between;gap:15px;padding:5px 0}.finance-tabs button{padding:9px 13px}.setting-card{margin-bottom:12px}.fee-row{align-items:flex-start;flex-direction:column}}
</style>
<div class="finance-shell">
<div class="finance-head"><div><h3>Payments & Finance</h3><p class="text-muted mb-0">Manage BookTKIT pricing, transactions and organizer settlements.</p></div></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif

<div class="finance-tabs mb-4" id="financeTabs">
<button data-tab="overview" class="active">Overview</button><button data-tab="pricing">Pricing & Fees</button><button data-tab="transactions">Transactions</button><a class="btn btn-outline-secondary" href="{{route('admin.organizer_payouts.index')}}">Settlements</a><a class="btn btn-outline-secondary" href="{{route('admin.payments.organizers')}}">Organizers</a><a class="btn btn-outline-secondary" href="{{route('admin.organizer_payouts.transfers')}}">Reconciliation</a>
</div>

<div class="finance-panel active" data-panel="overview">
<div class="row mb-4">
@foreach(['paid'=>'Gross Sales','platform'=>'BookTKIT Revenue','organizer'=>'Organizer Earnings','additional'=>'Additional Charges','refunded'=>'Refunded'] as $key=>$label)
<div class="col-6 col-lg mb-3"><div class="card metric-card"><div class="card-body"><small>{{$label}}</small><h3>₹{{number_format($summary[$key]/100,2)}}</h3></div></div></div>
@endforeach
</div>
<div class="card simple-card mb-4"><div class="card-body"><h5>How money moves</h5><p class="text-muted">Every sale is calculated by BookTKIT before payment. Organizer verification never stops ticket sales.</p><div class="flow"><span>Customer pays</span><b>→</b><span>BookTKIT / Razorpay</span><b>→</b><span>Fees calculated</span><b>→</b><span>Organizer earnings</span><b>→</b><span>Settlement</span></div></div></div>
<div class="card simple-card"><div class="card-header"><h5 class="mb-0">Recent transactions</h5></div><div class="card-body">@foreach($orders->take(5) as $o)<div class="fee-row"><div><strong>{{$eventNames[$o->event_id]??'Event #'.$o->event_id}}</strong><div class="help">{{$organizerNames[$o->organizer_id]??'Organizer #'.$o->organizer_id}} · {{strtoupper($o->sales_channel?:'web')}}</div></div><div class="text-right"><strong>₹{{number_format($o->customer_total/100,2)}}</strong><div class="help">{{ucfirst($o->status)}}</div></div></div>@endforeach</div></div>
</div>

<div class="finance-panel" data-panel="pricing">
<div class="pricing-tabs mb-3"><button data-price="global" class="active">Global Pricing</button><button data-price="eventtype">Event Type Pricing</button><button data-price="pos">POS Fees</button><button data-price="additional">Additional Fees</button><button data-price="special">Special Pricing</button></div>

<div class="pricing-panel active" data-price-panel="global"><div class="card simple-card"><div class="card-body"><h4>Default BookTKIT Pricing</h4><p class="text-muted">This is the default fee when no event, organizer or event-type pricing has been set.</p>
<form method="POST" action="{{route('admin.payments.fee_rules.store')}}">@csrf<input type="hidden" name="name" value="Global default"><input type="hidden" name="scope" value="global"><input type="hidden" name="sales_channel" value="any"><input type="hidden" name="priority" value="0">
<div class="row"><div class="col-md-3"><label>Platform fee</label><div class="input-group"><input class="form-control" type="number" step=".01" min="0" max="100" name="percentage" value="0"><div class="input-group-append"><span class="input-group-text">%</span></div></div></div><div class="col-md-3"><label>Fixed fee</label><div class="input-group"><div class="input-group-prepend"><span class="input-group-text">₹</span></div><input class="form-control" type="number" step=".01" min="0" name="fixed_amount_rupees" value="0"></div></div><div class="col-md-3"><label>Who pays?</label><select class="form-control" name="fee_bearer"><option value="included">Organizer</option><option value="additional">Customer</option></select></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary btn-block">Save Default Pricing</button></div></div></form>
</div></div>
<div class="card simple-card mt-3"><div class="card-body"><h5>Current default</h5>@php($globals=$feeRules->where('scope','global')->where('is_active',true))@forelse($globals as $r)<div class="fee-row"><div><strong>{{$r->name}}</strong><div class="help">Used when no more specific pricing applies</div></div><div><strong>{{rtrim(rtrim(number_format($r->percentage,2),'0'),'.')}}% @if($r->fixed_amount)+ ₹{{number_format($r->fixed_amount/100,2)}}@endif</strong> · {{$r->fee_bearer==='additional'?'Customer pays':'Organizer pays'}} <form class="d-inline" method="POST" action="{{route('admin.payments.fee_rules.destroy',$r->id)}}">@csrf @method('DELETE')<button class="btn btn-link btn-sm text-danger">Disable</button></form></div></div>@empty<p class="text-muted mb-0">No global pricing set. Legacy organizer pricing is currently used where available.</p>@endforelse</div></div></div>

<div class="pricing-panel" data-price-panel="eventtype"><div class="row">
@foreach(['venue'=>'Venue Events','online'=>'Online Events','box_office'=>'Box Office Events'] as $type=>$label)
<div class="col-lg-4"><div class="card simple-card h-100"><div class="card-body"><h5>{{$label}}</h5><p class="help">Overrides the global default for {{$label}}.</p>@php($current=$feeRules->where('scope','event_type')->where('event_type',$type)->where('is_active',true)->first())@if($current)<h3>{{rtrim(rtrim(number_format($current->percentage,2),'0'),'.')}}% @if($current->fixed_amount)<small>+ ₹{{number_format($current->fixed_amount/100,2)}}</small>@endif</h3><p>{{$current->fee_bearer==='additional'?'Customer pays':'Organizer pays'}}</p>@endif
<form method="POST" action="{{route('admin.payments.fee_rules.store')}}">@csrf<input type="hidden" name="name" value="{{$label}} pricing"><input type="hidden" name="scope" value="event_type"><input type="hidden" name="event_type" value="{{$type}}"><input type="hidden" name="sales_channel" value="any"><input type="hidden" name="priority" value="0"><label>Percentage</label><input class="form-control mb-2" type="number" step=".01" min="0" max="100" name="percentage" value="{{$current->percentage??0}}"><label>Fixed fee ₹</label><input class="form-control mb-2" type="number" step=".01" min="0" name="fixed_amount_rupees" value="{{isset($current)?$current->fixed_amount/100:0}}"><label>Paid by</label><select class="form-control mb-3" name="fee_bearer"><option value="included">Organizer</option><option value="additional" {{isset($current)&&$current->fee_bearer==='additional'?'selected':''}}>Customer</option></select><button class="btn btn-primary btn-block">Save {{$label}}</button></form></div></div></div>
@endforeach
</div></div>

<div class="pricing-panel" data-price-panel="pos"><div class="card simple-card"><div class="card-body"><h4>POS Sales Fee</h4><p class="text-muted">Applied only when tickets are sold from BookTKIT POS. Online sales continue using their normal event pricing.</p>@php($pos=$feeRules->where('sales_channel','pos')->where('is_active',true)->first())
<form method="POST" action="{{route('admin.payments.fee_rules.store')}}">@csrf<input type="hidden" name="name" value="POS sales pricing"><input type="hidden" name="scope" value="global"><input type="hidden" name="sales_channel" value="pos"><input type="hidden" name="priority" value="10"><div class="row"><div class="col-md-3"><label>Percentage fee</label><input class="form-control" type="number" step=".01" min="0" max="100" name="percentage" value="{{$pos->percentage??0}}"></div><div class="col-md-3"><label>Per order ₹</label><input class="form-control" type="number" step=".01" min="0" name="fixed_amount_rupees" value="{{isset($pos)?$pos->fixed_amount/100:0}}"></div><div class="col-md-3"><label>Per ticket ₹</label><input class="form-control" type="number" step=".01" min="0" name="per_ticket_rupees" value="{{isset($pos)?$pos->per_ticket_amount/100:0}}"></div><div class="col-md-3"><label>Paid by</label><select class="form-control" name="fee_bearer"><option value="included">Organizer</option><option value="additional" {{isset($pos)&&$pos->fee_bearer==='additional'?'selected':''}}>Customer</option></select></div></div><button class="btn btn-primary mt-3">Save POS Pricing</button></form></div></div></div>

<div class="pricing-panel" data-price-panel="additional"><div class="card simple-card"><div class="card-body d-flex justify-content-between align-items-center flex-wrap"><div><h4>Additional Event Charges</h4><p class="text-muted mb-0">Wristbands, RFID cards, parking, delivery, physical passes and other event charges.</p></div><button class="btn btn-primary" data-toggle="modal" data-target="#additionalFeeModal">+ Add Event Charge</button></div></div><div class="card simple-card mt-3"><div class="card-body">@forelse($additionalFees as $fee)<div class="fee-row"><div><strong>{{$eventNames[$fee->event_id]??'Event #'.$fee->event_id}} — {{$fee->name}}</strong><div class="help">@if($fee->percentage){{$fee->percentage}}% @else ₹{{number_format($fee->fixed_amount/100,2)}} @endif · {{str_replace('_',' ',$fee->application)}} · {{ucfirst($fee->fee_bearer)}} pays · {{!empty($fee->metadata['sales_channels'])?implode(', ',$fee->metadata['sales_channels']):'All channels'}} · {{$fee->is_mandatory?'Required':'Optional'}}</div></div>@if($fee->is_active)<form method="POST" action="{{route('admin.payments.additional_fees.destroy',$fee->id)}}">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Disable</button></form>@else<span class="status-pill">Disabled</span>@endif</div>@empty<p class="text-muted mb-0">No additional event charges configured.</p>@endforelse</div></div></div>

<div class="pricing-panel" data-price-panel="special"><div class="card simple-card"><div class="card-body"><h4>Special Pricing</h4><p class="text-muted">Use this only when a specific organizer or event has negotiated pricing. It automatically overrides event-type and global pricing.</p><form method="POST" action="{{route('admin.payments.fee_rules.store')}}">@csrf<div class="row"><div class="col-md-3"><label>Pricing for</label><select class="form-control" name="scope" id="specialScope"><option value="organizer">Specific organizer</option><option value="event">Specific event</option></select></div><div class="col-md-3 special-organizer"><label>Organizer</label><select class="form-control" name="organizer_id"><option value="">Choose organizer</option>@foreach($organizers as $o)<option value="{{$o->id}}">{{$o->username?:$o->email}}</option>@endforeach</select></div><div class="col-md-3 special-event" style="display:none"><label>Event</label><select class="form-control" name="event_id"><option value="">Choose event</option>@foreach($events as $e)<option value="{{$e->id}}">{{$eventNames[$e->id]}}</option>@endforeach</select></div><div class="col-md-3"><label>Percentage</label><input class="form-control" type="number" step=".01" min="0" max="100" name="percentage" value="0"></div><div class="col-md-3"><label>Fixed ₹</label><input class="form-control" type="number" step=".01" min="0" name="fixed_amount_rupees" value="0"></div></div><input type="hidden" name="name" value="Special pricing"><input type="hidden" name="sales_channel" value="any"><input type="hidden" name="priority" value="20"><div class="row mt-3"><div class="col-md-3"><label>Paid by</label><select class="form-control" name="fee_bearer"><option value="included">Organizer</option><option value="additional">Customer</option></select></div></div><button class="btn btn-primary mt-3">Save Special Pricing</button></form></div></div></div>
</div>

<div class="finance-panel" data-panel="transactions"><div class="card simple-card"><div class="card-header"><h5 class="mb-0">Transactions</h5></div><div class="card-body">
<div class="desktop-transactions table-responsive"><table class="table"><thead><tr><th>Transaction</th><th>Event</th><th>Organizer</th><th>Channel</th><th>Customer Paid</th><th>BookTKIT Fee</th><th>Organizer Gets</th><th>Status</th></tr></thead><tbody>@foreach($orders as $o)<tr><td>#{{strtoupper(substr(str_replace('-','',$o->uuid),0,10))}}</td><td>{{$eventNames[$o->event_id]??'Event #'.$o->event_id}}</td><td>{{$organizerNames[$o->organizer_id]??'Organizer #'.$o->organizer_id}}</td><td>{{strtoupper($o->sales_channel?:'web')}}</td><td>₹{{number_format($o->customer_total/100,2)}}</td><td>₹{{number_format(($o->platform_fee+$o->pos_fee)/100,2)}}</td><td>₹{{number_format($o->organizer_amount/100,2)}}</td><td><span class="status-pill">{{ucfirst($o->status)}}</span></td></tr>@endforeach</tbody></table></div>
<div class="mobile-transactions">@foreach($orders as $o)<div class="txn-card"><div class="txn-line"><strong>{{$eventNames[$o->event_id]??'Event #'.$o->event_id}}</strong><span class="status-pill">{{ucfirst($o->status)}}</span></div><div class="help">{{$organizerNames[$o->organizer_id]??'Organizer #'.$o->organizer_id}} · {{strtoupper($o->sales_channel?:'web')}} · #{{strtoupper(substr(str_replace('-','',$o->uuid),0,8))}}</div><hr><div class="txn-line"><span>Customer paid</span><strong>₹{{number_format($o->customer_total/100,2)}}</strong></div><div class="txn-line"><span>BookTKIT fee</span><span>₹{{number_format(($o->platform_fee+$o->pos_fee)/100,2)}}</span></div><div class="txn-line"><span>Organizer gets</span><strong>₹{{number_format($o->organizer_amount/100,2)}}</strong></div></div>@endforeach</div>
{{$orders->links()}}</div></div></div>
</div>

<div class="modal fade" id="additionalFeeModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{route('admin.payments.additional_fees.store')}}">@csrf<div class="modal-header"><h5 class="modal-title">Add Event Charge</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="row"><div class="col-md-6"><label>Event</label><select class="form-control" name="event_id" required><option value="">Search / choose event</option>@foreach($events as $e)<option value="{{$e->id}}">{{$eventNames[$e->id]}}</option>@endforeach</select></div><div class="col-md-3"><label>Fee type</label><select class="form-control" id="feePreset"><option value="wristband">Wristband</option><option value="rfid_card">RFID Card</option><option value="physical_pass">Physical Pass</option><option value="parking">Parking</option><option value="delivery">Delivery</option><option value="service_fee">Service Fee</option><option value="other">Other</option></select></div><div class="col-md-3"><label>Name</label><input class="form-control" name="name" id="feeName" value="Wristband" required><input type="hidden" name="code" id="feeCode" value="wristband"></div></div><div class="row mt-3"><div class="col-md-3"><label>Charge type</label><select class="form-control" name="calculation_type"><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></div><div class="col-md-3"><label>Amount ₹</label><input class="form-control" type="number" step=".01" min="0" name="fixed_amount_rupees" value="0"></div><div class="col-md-3"><label>Percentage</label><input class="form-control" type="number" step=".01" min="0" max="100" name="percentage" value="0"></div><div class="col-md-3"><label>Charge</label><select class="form-control" name="application"><option value="per_ticket">Per ticket</option><option value="per_order">Per order</option></select></div></div><div class="row mt-3"><div class="col-md-3"><label>Paid by</label><select class="form-control" name="fee_bearer"><option value="customer">Customer</option><option value="organizer">Organizer</option></select></div><div class="col-md-5"><label>Applies to</label><div><label class="mr-2"><input type="checkbox" name="sales_channels[]" value="web" checked> Website</label><label class="mr-2"><input type="checkbox" name="sales_channels[]" value="mobile" checked> Mobile</label><label><input type="checkbox" name="sales_channels[]" value="pos" checked> POS</label></div></div><div class="col-md-2"><label><input type="checkbox" name="is_mandatory" value="1"> Required</label></div><div class="col-md-2"><label><input type="checkbox" name="is_taxable" value="1"> Taxable</label></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button class="btn btn-primary">Add Fee</button></div></form></div></div></div>

<script>
(function(){function activate(group,key){document.querySelectorAll(group+' button').forEach(b=>b.classList.toggle('active',b.dataset.tab===key||b.dataset.price===key));if(group==='#financeTabs'){document.querySelectorAll('.finance-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===key));localStorage.setItem('financeTab',key)}else{document.querySelectorAll('.pricing-panel').forEach(p=>p.classList.toggle('active',p.dataset.pricePanel===key));localStorage.setItem('pricingTab',key)}}document.querySelectorAll('#financeTabs button').forEach(b=>b.onclick=()=>activate('#financeTabs',b.dataset.tab));document.querySelectorAll('.pricing-tabs button').forEach(b=>b.onclick=()=>activate('.pricing-tabs',b.dataset.price));activate('#financeTabs','{{session('finance_tab')}}'||localStorage.getItem('financeTab')||'overview');activate('.pricing-tabs',localStorage.getItem('pricingTab')||'global');var scope=document.getElementById('specialScope');if(scope)scope.onchange=function(){document.querySelector('.special-organizer').style.display=this.value==='organizer'?'block':'none';document.querySelector('.special-event').style.display=this.value==='event'?'block':'none'};var preset=document.getElementById('feePreset');if(preset)preset.onchange=function(){var label=this.options[this.selectedIndex].text;document.getElementById('feeName').value=this.value==='other'?'':label;document.getElementById('feeCode').value=this.value};})();
</script>
@endsection