@extends('organizer.layout')
@section('content')
<div class="page-header"><h4 class="page-title">{{ __('Passes & Access') }} — {{ eventSlug(1,$event->id) }}</h4></div>
<div class="row"><div class="col-lg-5"><div class="card"><div class="card-header"><strong>{{ __('Add Pass Product') }}</strong></div><div class="card-body">
<form method="POST" action="{{ route('organizer.event.passes.store',$event->id) }}">@csrf
<div class="form-group"><label>Pass name *</label><input class="form-control" name="name" required placeholder="Season Pass / Weekend Pass"></div>
<div class="form-row"><div class="form-group col-md-6"><label>Code *</label><input class="form-control" name="code" required placeholder="SEASON"></div><div class="form-group col-md-6"><label>Pass type *</label><select class="form-control" name="pass_type">@foreach(['single_day'=>'Single Day','any_one_day'=>'Any One Day','multi_day'=>'Multi-Day','weekend'=>'Weekend','combo'=>'Combo Days','season'=>'Season Pass','group'=>'Group','couple'=>'Couple','custom'=>'Custom'] as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></div></div>
<div class="form-group"><label>Underlying ticket/category *</label><select class="form-control" name="ticket_id" required>@foreach($tickets as $ticket)<option value="{{ $ticket->id }}">{{ $ticket->title ?? ('Ticket #'.$ticket->id) }}</option>@endforeach</select><small class="text-muted">Existing ticket controls the shared ticket category; this pass controls price and eligible dates.</small></div>
<div class="form-row"><div class="form-group col-md-6"><label>Price *</label><input class="form-control" type="number" min="0" step="0.01" name="price" required></div><div class="form-group col-md-6"><label>Max per order *</label><input class="form-control" type="number" min="1" max="50" name="max_per_order" value="10" required></div></div>
<div class="form-group"><label>Date rule *</label><select class="form-control" name="selection_mode" id="passSelectionMode"><option value="fixed_dates">Fixed selected dates</option><option value="all_dates">All event dates</option><option value="choose_n">Customer chooses N dates</option></select></div>
<div class="form-group" id="chooseCountWrap" style="display:none"><label>Number of dates customer chooses</label><input class="form-control" type="number" min="1" name="choose_count"></div>
<div class="form-group"><label>Eligible event dates *</label><div class="border rounded p-2" style="max-height:180px;overflow:auto">@forelse($dates as $date)<label class="d-block"><input type="checkbox" name="event_date_ids[]" value="{{ $date->id }}"> {{ $date->start_date }} {{ $date->start_time }}@if($date->end_date) → {{ $date->end_date }} {{ $date->end_time }}@endif</label>@empty<small class="text-danger">Add event dates before creating passes.</small>@endforelse</div></div>
<div class="form-row"><div class="form-group col-md-6"><label>Inventory</label><select class="form-control" name="inventory_type"><option value="unlimited">Unlimited</option><option value="limited">Limited</option></select></div><div class="form-group col-md-6"><label>Pass stock</label><input class="form-control" type="number" min="1" name="inventory_quantity"></div></div>
<div class="form-group"><label>Sales channels *</label><div>@foreach(['web'=>'Website','mobile'=>'Mobile','pos'=>'POS','box_office'=>'Box Office'] as $k=>$v)<label class="mr-3"><input type="checkbox" name="sales_channels[]" value="{{ $k }}" checked> {{ $v }}</label>@endforeach</div></div>
<div class="form-group"><label>Allowed credentials</label><div>@foreach(['digital_qr'=>'Digital QR','printed_qr'=>'Printed QR','qr_wristband'=>'QR Wristband','rfid_wristband'=>'RFID Wristband','rfid_card'=>'RFID Card','printed_id'=>'Printed ID Card'] as $k=>$v)<label class="d-block"><input type="checkbox" name="credential_types[]" value="{{ $k }}"> {{ $v }}</label>@endforeach</div></div>
<input type="hidden" name="admissions_per_holder" value="1"><input type="hidden" name="active" value="1"><button class="btn btn-primary btn-block" {{ $dates->isEmpty()||$tickets->isEmpty()?'disabled':'' }}>Add Pass</button></form>
</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Configured Passes</strong><a class="btn btn-sm btn-outline-primary" href="{{ route('organizer.access.index',['event_id'=>$event->id]) }}">Manage wristbands / RFID / gates</a></div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Pass</th><th>Dates</th><th>Price</th><th>Sold</th><th>Status</th><th></th></tr></thead><tbody>@forelse($passes as $pass)<tr><td><strong>{{ $pass->name }}</strong><br><small>{{ str_replace('_',' ',ucfirst($pass->pass_type)) }}</small></td><td>{{ $pass->dates->count() }} date(s) @if($pass->selection_mode==='choose_n') / choose {{ $pass->choose_count }} @endif</td><td>₹{{ number_format($pass->price/100,2) }}</td><td>{{ $pass->sold_quantity }}@if($pass->inventory_type==='limited') / {{ $pass->inventory_quantity }}@endif</td><td>{{ $pass->active?'Active':'Disabled' }}</td><td>@if(!$pass->sold_quantity)<form method="POST" action="{{ route('organizer.event.passes.destroy',[$event->id,$pass->id]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center py-4 text-muted">No pass products yet. Existing normal tickets continue to work unchanged.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('passSelectionMode'),w=document.getElementById('chooseCountWrap');if(s)s.addEventListener('change',()=>w.style.display=s.value==='choose_n'?'block':'none')});</script>
@endsection
