<?php
namespace App\Http\Controllers\BackEnd;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use App\Models\Payments\OrganizerPaymentProfile;use App\Models\Payments\PaymentFeeRule;use App\Models\Payments\EventAdditionalFee;use App\Models\Payments\PaymentOrder;
class PaymentFinanceController extends Controller{
 public function index(Request $r){$q=PaymentOrder::with(['transfers','refunds','feeLines'])->latest();if($r->filled('status'))$q->where('status',$r->status);if($r->filled('organizer_id'))$q->where('organizer_id',$r->organizer_id);if($r->filled('sales_channel'))$q->where('sales_channel',$r->sales_channel);$orders=$q->paginate(25)->withQueryString();$paid=PaymentOrder::where('status','paid');$summary=['paid'=>(int)(clone $paid)->sum('customer_total'),'platform'=>(int)(clone $paid)->sum('platform_fee')+(int)(clone $paid)->sum('pos_fee'),'organizer'=>(int)(clone $paid)->sum('organizer_amount'),'refunded'=>(int)PaymentOrder::sum('refunded_amount')];$feeRules=PaymentFeeRule::orderByDesc('priority')->orderByDesc('id')->get();$additionalFees=EventAdditionalFee::latest()->limit(100)->get();return view('backend.payments.finance',compact('orders','summary','feeRules','additionalFees'));}
 public function storeFeeRule(Request $r){$d=$this->ruleData($r);PaymentFeeRule::create($d);return back()->with('success','Payment fee rule created.');}
 public function updateFeeRule(Request $r,$id){PaymentFeeRule::findOrFail($id)->update($this->ruleData($r));return back()->with('success','Payment fee rule updated. Existing payment snapshots are unchanged.');}
 public function destroyFeeRule($id){PaymentFeeRule::findOrFail($id)->update(['is_active'=>false]);return back()->with('success','Payment fee rule disabled for new orders.');}
 private function ruleData(Request $r):array{$v=$r->validate(['name'=>'required|string|max:120','scope'=>'required|in:global,event_type,organizer,event','organizer_id'=>'nullable|integer|min:1','event_id'=>'nullable|integer|min:1','event_type'=>'nullable|in:online,venue,box_office','sales_channel'=>'required|in:any,web,mobile,pos,admin','percentage'=>'required|numeric|min:0|max:100','fixed_amount_rupees'=>'required|numeric|min:0','per_ticket_rupees'=>'nullable|numeric|min:0','fee_bearer'=>'required|in:included,additional','priority'=>'required|integer|min:0|max:100000']);$v['fixed_amount']=(int)round($v['fixed_amount_rupees']*100);$v['per_ticket_amount']=(int)round(($v['per_ticket_rupees']??0)*100);unset($v['fixed_amount_rupees'],$v['per_ticket_rupees']);$v['fee_type']=$v['percentage']>0&&$v['fixed_amount']>0?'hybrid':($v['percentage']>0?'percentage':'fixed');$v['is_active']=true;return $v;}
 public function storeAdditionalFee(Request $r){$d=$r->validate(['event_id'=>'required|integer|exists:events,id','code'=>'required|string|max:60','name'=>'required|string|max:120','calculation_type'=>'required|in:fixed,percentage','application'=>'required|in:per_order,per_ticket','fixed_amount_rupees'=>'required|numeric|min:0','percentage'=>'required|numeric|min:0|max:100','fee_bearer'=>'required|in:customer,organizer','sales_channels'=>'nullable|array','sales_channels.*'=>'in:web,mobile,pos,admin']);$channels=$d['sales_channels']??[];$d['fixed_amount']=(int)round($d['fixed_amount_rupees']*100);unset($d['fixed_amount_rupees'],$d['sales_channels']);$d['is_mandatory']=$r->boolean('is_mandatory');$d['is_taxable']=$r->boolean('is_taxable');$d['is_active']=true;$d['metadata']=['sales_channels'=>$channels];EventAdditionalFee::updateOrCreate(['event_id'=>$d['event_id'],'code'=>$d['code']],$d);return back()->with('success','Additional fee saved.');}
 public function disableAdditionalFee($id){EventAdditionalFee::findOrFail($id)->update(['is_active'=>false]);return back()->with('success','Additional fee disabled for new orders.');}
 public function organizers(){$profiles=OrganizerPaymentProfile::with('organizer')->latest()->paginate(25);return view('backend.payments.organizers',compact('profiles'));}
 public function updateOrganizer(Request $r,$id){$p=OrganizerPaymentProfile::firstOrCreate(['organizer_id'=>$id]);$d=$r->validate(['preferred_settlement_mode'=>'required|in:booktkit_managed,razorpay_split','razorpay_account_id'=>'nullable|string|max:100','razorpay_status'=>'required|string|max:50','split_enabled'=>'nullable|boolean']);$d['split_enabled']=$r->boolean('split_enabled');$p->update($d);return back()->with('success','Organizer settlement preference updated. Ticket sales remain active regardless of KYC status.');}
}