<?php
namespace App\Http\Controllers\BackEnd;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use App\Models\Payments\PaymentFeeRule;use App\Models\Payments\EventAdditionalFee;use App\Models\Payments\PaymentOrder;
class PaymentFinanceController extends Controller{
 public function index(Request $r){$q=PaymentOrder::with(['transfers','refunds','feeLines'])->latest();if($r->filled('status'))$q->where('status',$r->status);if($r->filled('organizer_id'))$q->where('organizer_id',$r->organizer_id);if($r->filled('sales_channel'))$q->where('sales_channel',$r->sales_channel);$orders=$q->paginate(25)->withQueryString();$summary=['paid'=>(int)PaymentOrder::where('status','paid')->sum('customer_total'),'platform'=>(int)PaymentOrder::where('status','paid')->sum('platform_fee'),'organizer'=>(int)PaymentOrder::where('status','paid')->sum('organizer_amount'),'refunded'=>(int)PaymentOrder::sum('refunded_amount')];$feeRules=PaymentFeeRule::orderByDesc('priority')->latest()->get();$additionalFees=EventAdditionalFee::latest()->limit(100)->get();return view('backend.payments.finance',compact('orders','summary','feeRules','additionalFees'));}
 public function storeFeeRule(Request $r){$d=$r->validate(['name'=>'required|string|max:120','scope'=>'required|in:global,event_type,organizer,event','event_type'=>'nullable|string|max:30','sales_channel'=>'required|in:any,web,mobile,pos,admin','organizer_id'=>'nullable|integer','event_id'=>'nullable|integer','percentage'=>'required|numeric|min:0|max:100','fixed_amount_rupees'=>'required|numeric|min:0','per_ticket_rupees'=>'nullable|numeric|min:0','fee_bearer'=>'required|in:included,additional','priority'=>'required|integer|min:0']);$d['fixed_amount']=(int)round($d['fixed_amount_rupees']*100);$d['per_ticket_amount']=(int)round(($d['per_ticket_rupees']??0)*100);unset($d['fixed_amount_rupees'],$d['per_ticket_rupees']);$d['fee_type']=$d['percentage']>0&&$d['fixed_amount']>0?'hybrid':($d['percentage']>0?'percentage':'fixed');$d['is_active']=true;PaymentFeeRule::create($d);return back()->with('success','Fee rule created.');}
 public function destroyFeeRule($id){PaymentFeeRule::findOrFail($id)->update(['is_active'=>false]);return back()->with('success','Fee rule disabled for new orders.');}
 public function storeAdditionalFee(Request $r){$d=$r->validate(['event_id'=>'required|integer|exists:events,id','code'=>'required|string|max:60','name'=>'required|string|max:120','calculation_type'=>'required|in:fixed,percentage','application'=>'required|in:per_order,per_ticket','fixed_amount_rupees'=>'required|numeric|min:0','percentage'=>'required|numeric|min:0|max:100','fee_bearer'=>'required|in:customer,organizer','sales_channels'=>'nullable|array']);$d['fixed_amount']=(int)round($d['fixed_amount_rupees']*100);unset($d['fixed_amount_rupees']);$d['is_mandatory']=$r->boolean('is_mandatory');$d['is_taxable']=$r->boolean('is_taxable');$d['is_active']=true;$d['metadata']=['sales_channels'=>$d['sales_channels']??[]];unset($d['sales_channels']);EventAdditionalFee::updateOrCreate(['event_id'=>$d['event_id'],'code'=>$d['code']],$d);return back()->with('success','Additional fee saved.');}
 public function disableAdditionalFee($id){EventAdditionalFee::findOrFail($id)->update(['is_active'=>false]);return back()->with('success','Additional fee disabled.');}
}