@extends('organizer.layout')
@section('content')
<div class="page-header"><h4 class="page-title">BookTKIT Access</h4></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card mb-3"><div class="card-body"><form method="get" action="{{ route('organizer.access.index') }}"><label>Event</label><select name="event_id" class="form-control" onchange="this.form.submit()">@foreach($events as $e)<option value="{{ $e->id }}" @selected($event && $event->id===$e->id)>{{ optional($e->information)->title ?: 'Event #'.$e->id }}</option>@endforeach</select></form></div></div>
@if($event)
<div class="row mb-3">
@foreach(['Inside'=>$stats['inside'],'Outside'=>$stats['outside'],'Entries'=>$stats['entries'],'Exits'=>$stats['exits'],'Active Credentials'=>$stats['credentials']] as $label=>$value)
<div class="col-6 col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">{{ $label }}</div><div class="h3 mb-0">{{ $value }}</div></div></div></div>
@endforeach
</div>
<div class="row">
<div class="col-lg-6"><div class="card mb-3"><div class="card-header"><strong>Access Zones</strong></div><div class="card-body">
<form method="post" action="{{ route('organizer.access.zone') }}">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><div class="row"><div class="col-md-5 form-group"><input name="name" class="form-control" placeholder="VIP / Main Venue" required></div><div class="col-md-4 form-group"><input name="code" class="form-control" placeholder="vip" required></div><div class="col-md-3"><button class="btn btn-primary btn-block">Add Zone</button></div></div></form>
@foreach($zones as $zone)<span class="badge badge-light border mr-2">{{ $zone->name }} · {{ $zone->code }}</span>@endforeach
</div></div></div>
<div class="col-lg-6"><div class="card mb-3"><div class="card-header"><strong>Gates / Checkpoints</strong></div><div class="card-body">
<form method="post" action="{{ route('organizer.access.gate') }}">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><div class="form-group"><input name="name" class="form-control" placeholder="Gate A" required></div><div class="row"><div class="col-md-4"><input name="code" class="form-control" placeholder="gate-a" required></div><div class="col-md-3"><select name="mode" class="form-control"><option value="entry_exit">Entry + Exit</option><option value="entry">Entry only</option><option value="exit">Exit only</option></select></div><div class="col-md-3"><select name="zone_id" class="form-control"><option value="">No zone</option>@foreach($zones as $zone)<option value="{{ $zone->id }}">{{ $zone->name }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-dark btn-block">Add</button></div></div></form>
<div class="mt-2">@foreach($gates as $gate)<span class="badge badge-light border mr-2">{{ $gate->name }} · {{ str_replace('_',' / ',$gate->mode) }}</span>@endforeach</div>
</div></div></div>
</div>
<div class="row">
<div class="col-lg-7"><div class="card mb-3"><div class="card-header"><strong>Access Policy</strong></div><div class="card-body">
<form method="post" action="{{ route('organizer.access.policy', $event->id) }}">@csrf @method('PUT')
<div class="form-group"><label><input type="checkbox" name="is_enabled" value="1" @checked(optional($policy)->is_enabled)> Enable BookTKIT Access for this event</label></div>
<div class="form-group"><label>Credential mode</label><select name="credential_mode" class="form-control"><option value="ticket_only">Ticket QR only</option><option value="physical_required" @selected(optional($policy)->credential_mode==='physical_required')>Physical credential required</option><option value="hybrid" @selected(optional($policy)->credential_mode==='hybrid')>Hybrid</option></select></div>
<div class="form-group"><label>Credential types</label><div>@foreach(['qr_wristband'=>'QR wristband','rfid_card'=>'RFID card','nfc_wristband'=>'NFC wristband','qr_badge'=>'QR badge','physical_id'=>'Physical ID'] as $v=>$label)<label class="mr-3"><input type="checkbox" name="credential_types[]" value="{{ $v }}" @checked(in_array($v, optional($policy)->credential_types ?: []))> {{ $label }}</label>@endforeach</div></div>
<div class="row"><div class="col-md-6 form-group"><label>Re-entry</label><select name="reentry_policy" class="form-control"><option value="none">No re-entry</option><option value="limited" @selected(optional($policy)->reentry_policy==='limited')>Limited</option><option value="unlimited" @selected(optional($policy)->reentry_policy==='unlimited')>Unlimited</option></select></div><div class="col-md-6 form-group"><label>Max re-entries</label><input name="max_reentries" type="number" min="1" class="form-control" value="{{ optional($policy)->max_reentries }}"></div></div>
<div class="form-group"><label><input type="checkbox" name="collection_required" value="1" @checked(optional($policy)->collection_required)> Collection required at venue</label> <label class="ml-3"><input type="checkbox" name="allow_ticket_qr_before_assignment" value="1" @checked(!$policy || $policy->allow_ticket_qr_before_assignment)> Allow ticket QR before assignment</label></div>
<div class="form-group"><label><input type="checkbox" name="exit_scan_required" value="1" @checked(optional($policy)->exit_scan_required)> Exit scan required</label> <label class="ml-3"><input type="checkbox" name="replacement_allowed" value="1" @checked(!$policy || $policy->replacement_allowed)> Allow replacements</label></div>
<div class="form-group"><label>Max replacements</label><input name="max_replacements" type="number" min="1" class="form-control" value="{{ optional($policy)->max_replacements }}"></div><div class="form-group"><label>Replacement fee (INR)</label><input name="replacement_fee" type="number" min="0" step="0.01" class="form-control" value="{{ number_format(data_get(optional($policy)->metadata, 'replacement_fee_paise', 0) / 100, 2, '.', '') }}"><small class="text-muted">Set 0 for free replacement.</small></div>
<button class="btn btn-primary">Save Access Policy</button></form></div></div></div>
<div class="col-lg-5"><div class="card mb-3"><div class="card-header"><strong>Credential Inventory</strong></div><div class="card-body"><form method="post" action="{{ route('organizer.access.batch') }}">@csrf<input type="hidden" name="event_id" value="{{ $event->id }}"><div class="form-group"><label>Type</label><select name="credential_type" class="form-control"><option value="qr_wristband">QR wristband</option><option value="rfid_card">RFID card</option><option value="nfc_wristband">NFC wristband</option><option value="qr_badge">QR badge</option><option value="physical_id">Physical ID</option></select></div><div class="form-group"><label>Batch code</label><input name="batch_code" class="form-control" required></div><div class="form-group"><label>Identifiers (one per line or comma-separated)</label><textarea name="identifiers" rows="6" class="form-control" required></textarea></div><button class="btn btn-dark">Import Batch</button></form></div></div></div>
</div>
<div class="row">
<div class="col-lg-6"><div class="card mb-3"><div class="card-header"><strong>Issue / Collect Credential</strong></div><div class="card-body"><p class="text-muted">Scan the attendee ticket QR, then scan the unassigned wristband/card identifier.</p><form method="post" action="{{ route('organizer.access.assign') }}">@csrf<div class="form-group"><label>Ticket QR / UUID</label><input name="ticket_reference" class="form-control" required autofocus></div><div class="form-group"><label>Credential identifier</label><input name="credential_identifier" class="form-control" required></div><button class="btn btn-success">Assign & Activate</button></form></div></div></div>
<div class="col-lg-6"><div class="card mb-3"><div class="card-header"><strong>Replace Lost / Damaged Credential</strong></div><div class="card-body"><form method="post" action="{{ route('organizer.access.replace') }}">@csrf<div class="form-group"><label>Ticket QR / UUID</label><input name="ticket_reference" class="form-control" required></div><div class="form-group"><label>New credential identifier</label><input name="credential_identifier" class="form-control" required></div><div class="form-group"><label>Reason</label><select name="reason" class="form-control"><option value="lost">Lost</option><option value="damaged">Damaged</option><option value="unreadable">Unreadable</option><option value="rfid_malfunction">RFID malfunction</option><option value="staff_replacement">Staff replacement</option><option value="other">Other</option></select></div><button class="btn btn-warning">Revoke Old & Replace</button></form></div></div></div>
</div>
<div class="card mb-3"><div class="card-header"><strong>Gate Throughput</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Gate</th><th>Mode</th><th>Entries</th><th>Exits</th><th>Denied</th></tr></thead><tbody>@forelse($gateStats as $gate)<tr><td>{{ $gate->name }}</td><td>{{ strtoupper(str_replace('_',' / ',$gate->mode)) }}</td><td>{{ $gate->entries }}</td><td>{{ $gate->exits }}</td><td>{{ $gate->denied }}</td></tr>@empty<tr><td colspan="5" class="text-muted">Create gates to see throughput.</td></tr>@endforelse</tbody></table></div></div>
<div class="card mb-3"><div class="card-header"><strong>Live Access Activity</strong><span class="text-muted ml-2">latest 100 scans</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Time</th><th>Action</th><th>Result</th><th>Reason</th><th>Ticket</th></tr></thead><tbody>@forelse($scans as $scan)<tr><td>{{ \Carbon\Carbon::parse($scan->created_at)->format('d M H:i:s') }}</td><td>{{ strtoupper($scan->action) }}</td><td><span class="badge {{ $scan->result==='denied'?'badge-danger':'badge-success' }}">{{ ucfirst($scan->result) }}</span></td><td>{{ $scan->reason_code ?: '—' }}</td><td>#{{ $scan->issued_ticket_id }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No access scans yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><strong>Recent Assignments</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Ticket</th><th>Credential</th><th>Status</th><th>Assigned</th></tr></thead><tbody>@forelse($assignments as $a)<tr><td>{{ $a->ticket->uuid }}</td><td>{{ $a->credential->type }} · {{ $a->credential->display_code }}</td><td>{{ ucfirst($a->status) }}</td><td>{{ optional($a->assigned_at)->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="text-muted">No credentials assigned yet.</td></tr>@endforelse</tbody></table></div></div>
@endif
@endsection
