<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up(){
  Schema::create('box_office_holds',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('organizer_id')->constrained('organizers')->cascadeOnDelete();$t->foreignId('event_id')->constrained('events')->cascadeOnDelete();$t->foreignId('location_id')->constrained('box_office_locations')->cascadeOnDelete();$t->foreignId('staff_id')->nullable()->constrained('organizer_staff')->nullOnDelete();$t->json('items');$t->json('customer')->nullable();$t->string('status',20)->default('held');$t->timestamp('expires_at')->nullable();$t->timestamp('resumed_at')->nullable();$t->timestamps();$t->index(['organizer_id','status','expires_at'],'bo_hold_lookup_idx');});
  Schema::create('box_office_settings',function(Blueprint $t){$t->id();$t->foreignId('organizer_id')->nullable()->constrained('organizers')->cascadeOnDelete();$t->unsignedBigInteger('event_id')->nullable();$t->unsignedInteger('hold_minutes')->default(10);$t->boolean('allow_cash')->default(true);$t->boolean('allow_upi')->default(true);$t->boolean('allow_card')->default(true);$t->boolean('allow_other')->default(true);$t->boolean('require_customer_name')->default(true);$t->boolean('require_customer_phone')->default(true);$t->boolean('allow_aadhaar')->default(false);$t->boolean('allow_customer_photo')->default(true);$t->boolean('auto_email_ticket')->default(false);$t->unsignedSmallInteger('receipt_width_mm')->default(80);$t->timestamps();$t->unique(['organizer_id','event_id'],'bo_settings_owner_event_unique');});
  Schema::table('organizer_staff',function(Blueprint $t){$t->string('department',50)->default('box_office')->after('role');$t->string('job_title',100)->nullable()->after('department');$t->string('photo')->nullable()->after('phone');$t->text('notes')->nullable()->after('photo');});
  Schema::create('staff_audit_logs',function(Blueprint $t){$t->id();$t->foreignId('organizer_id')->nullable()->constrained('organizers')->nullOnDelete();$t->foreignId('staff_id')->nullable()->constrained('organizer_staff')->nullOnDelete();$t->unsignedBigInteger('admin_id')->nullable();$t->string('action',80);$t->json('meta')->nullable();$t->string('ip',64)->nullable();$t->timestamps();$t->index(['staff_id','created_at'],'staff_audit_staff_idx');});
 }
 public function down(){Schema::dropIfExists('staff_audit_logs');Schema::table('organizer_staff',function(Blueprint $t){$t->dropColumn(['department','job_title','photo','notes']);});Schema::dropIfExists('box_office_settings');Schema::dropIfExists('box_office_holds');}
};