@extends('organizer.layout')
@section('content')
<div class="page-header"><h4 class="page-title">Team</h4></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row"><div class="col-lg-5"><div class="card"><div class="card-header"><h4>Create staff member</h4></div><div class="card-body"><form method="post" action="{{ route('organizer.staff.store') }}">@csrf
<div class="form-group"><label>Name</label><input class="form-control" name="name" required></div><div class="form-group"><label>Username</label><input class="form-control" name="username" required></div><div class="form-group"><label>Email</label><input class="form-control" type="email" name="email"></div><div class="form-group"><label>Phone</label><input class="form-control" name="phone"></div><div class="form-group"><label>Temporary password</label><input class="form-control" type="password" name="password" minlength="8" required></div>
<div class="form-group"><label>Role</label><select class="form-control" name="role" required>@foreach($roles as $key=>$role)<option value="{{ $key }}">{{ $role['label'] }}</option>@endforeach</select></div>
<div class="form-group"><label>Special event</label><select class="form-control" name="event_id" required>@foreach($events as $event)<option value="{{ $event->id }}">{{ $event->title ?? ('Event #'.$event->id) }}</option>@endforeach</select></div>
<div class="form-group"><label>Box office location</label><select class="form-control" name="box_office_location_id"><option value="">Event-wide (ticket checker only)</option>@foreach($events as $event)@foreach($event->boxOfficeLocations as $loc)<option value="{{ $loc->id }}">{{ $event->title ?? ('Event #'.$event->id) }} — {{ $loc->name }}</option>@endforeach @endforeach</select></div>
<button class="btn btn-primary">Create staff</button></form></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-header"><h4>Staff</h4></div><div class="card-body table-responsive"><table class="table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Assignment</th><th></th></tr></thead><tbody>@forelse($staff as $member)@php($a=$member->assignments->first())<tr><td>{{ $member->name }}<br><small>{{ $member->username }}</small></td><td>{{ $roles[$member->role]['label'] ?? $member->role }}</td><td>{{ $member->active ? 'Active' : 'Disabled' }}</td><td>{{ $a ? 'Event #'.$a->event_id : '—' }} @if($a&&$a->box_office_location_id)/ Counter #{{ $a->box_office_location_id }}@endif</td><td><form method="post" action="{{ route('organizer.staff.update',$member->id) }}">@csrf @method('PUT')<input type="hidden" name="name" value="{{ $member->name }}"><input type="hidden" name="role" value="{{ $member->role }}"><input type="hidden" name="event_id" value="{{ optional($a)->event_id }}"><input type="hidden" name="box_office_location_id" value="{{ optional($a)->box_office_location_id }}"><input type="hidden" name="active" value="{{ $member->active ? 0 : 1 }}"><button class="btn btn-sm {{ $member->active?'btn-danger':'btn-success' }}">{{ $member->active?'Disable':'Enable' }}</button></form></td></tr>@empty<tr><td colspan="5">No staff yet.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection