@extends('organizer.layout')
@section('style')<style>.team-card{border:1px solid #edf0f5;border-radius:14px;padding:16px;height:100%;background:#fff}.team-photo{width:62px;height:62px;border-radius:50%;object-fit:cover;background:#f0f2f5}.team-avatar{width:62px;height:62px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#fff1e4;color:#d96d0b;font-size:22px;font-weight:800}.team-meta{font-size:12px;color:#778}.team-stat{background:#f7f8fa;border-radius:10px;padding:8px;text-align:center}.team-actions{display:flex;gap:6px;flex-wrap:wrap}</style>@endsection
@section('content')
<div class="page-header d-flex justify-content-between"><div><h4 class="page-title">Team</h4><p class="text-muted mb-0">Sales, Box Office, admissions and event operations staff</p></div><button class="btn btn-primary" data-toggle="modal" data-target="#addTeam">+ Add team member</button></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<div class="row">@forelse($staff as $m)@php($a=$m->assignments->first())<div class="col-xl-4 col-md-6 mb-3"><div class="team-card"><div class="d-flex align-items-center">@if($m->photo)<img class="team-photo mr-3" src="{{asset('storage/'.$m->photo)}}">@else<div class="team-avatar mr-3">{{strtoupper(substr($m->name,0,1))}}</div>@endif<div><h5 class="mb-1">{{$m->name}}</h5><div>{{$m->job_title ?: ($roles[$m->role]['label']??$m->role)}}</div><div class="team-meta">{{$departments[$m->department]??$m->department}} · {{$m->active?'Active':'Disabled'}}</div></div></div><div class="row mt-3"><div class="col-4"><div class="team-stat"><strong>{{$m->sales_count}}</strong><br><small>Sales</small></div></div><div class="col-8"><div class="team-stat"><strong>{{optional(optional($a)->event)->title ?? ('Event #'.optional($a)->event_id)}}</strong><br><small>{{optional(optional($a)->location)->name ?: 'Event-wide'}}</small></div></div></div><div class="team-meta mt-3">{{$m->username}} @if($m->phone) · {{$m->phone}}@endif<br>Last login: {{$m->last_login_at ? $m->last_login_at->diffForHumans() : 'Never'}}</div><div class="team-actions mt-3"><button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#edit{{$m->id}}">Edit</button><button class="btn btn-sm btn-outline-warning" data-toggle="modal" data-target="#pass{{$m->id}}">Reset password</button><form method="post" action="{{route('organizer.staff.destroy',$m->id)}}" onsubmit="return confirm('Delete this team member? Historical sales will be retained.')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></div></div>
<div class="modal fade" id="edit{{$m->id}}"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post" enctype="multipart/form-data" action="{{route('organizer.staff.update',$m->id)}}">@csrf @method('PUT')<div class="modal-header"><h5>Edit {{$m->name}}</h5><button class="close" data-dismiss="modal">×</button></div><div class="modal-body">@include('organizer.staff.partials.fields',['member'=>$m,'assignment'=>$a])</div><div class="modal-footer"><button class="btn btn-primary">Save profile</button></div></form></div></div></div>
<div class="modal fade" id="pass{{$m->id}}"><div class="modal-dialog"><div class="modal-content"><form method="post" action="{{route('organizer.staff.reset_password',$m->id)}}">@csrf<div class="modal-header"><h5>Reset staff password</h5></div><div class="modal-body"><input class="form-control" type="password" name="password" minlength="8" required placeholder="New temporary password"><small>All current staff API sessions will be revoked.</small></div><div class="modal-footer"><button class="btn btn-warning">Reset password</button></div></form></div></div></div>
@empty<div class="col-12"><div class="card"><div class="card-body text-center py-5">No team members yet. Add your first cashier, sales agent or ticket checker.</div></div></div>@endforelse</div>
<div class="modal fade" id="addTeam"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post" enctype="multipart/form-data" action="{{route('organizer.staff.store')}}">@csrf<div class="modal-header"><h5>Add team member</h5><button class="close" data-dismiss="modal">×</button></div><div class="modal-body">@include('organizer.staff.partials.fields',['member'=>null,'assignment'=>null])<div class="form-group"><label>Temporary password</label><input class="form-control" type="password" name="password" minlength="8" required></div></div><div class="modal-footer"><button class="btn btn-primary">Create team member</button></div></form></div></div></div>
@endsection